ProjetP1: adrien.h File Reference
adrien.h File Reference
#include "structure.h"
Functions
void creationPioche (Jeux *Jeu)
Carte creationCarte (int valeur, int tdb)
void afficherCarte (Carte carte, int etat)
: demande à l'utilisateur le niveau des bots
void seuiltdb (Jeux *Jeu, int idjoueur)
void classement (Jeux *Jeu)
void affclassement (Jeux *Jeu)
void supprimercarte (Carte *cartes, int *p_taille, int position)
void afficherMainJoueur (Joueur *joueur)
: Permet d'afficher la main du joueur
void placementSeries (Jeux *Jeu)
: La procédure récupère l'écart supérieu le plus petit et si la carte jouée est inférieure aux séries
Function Documentation
affclassement()
void affclassement (Jeux * Jeu)
Definition at line 132 of file adrien.c.
{
     printf(BORA);
     printf("━━━━━━━━━━━━━━━━━CLASSEMENT FINAL━━━━━━━━━━━━━━━━━ \n");
     for (int i = 0; i < Jeu->nbJoueurs; i++){
         printf("-------------------POSITION %d------------------- \n", i+1);
         printf("NOM: %s  ", Jeu->classementFinal[i].nomJoueur);
         if(i == 1){
             printf("       (dommage 2ème comme Arsenal)");
         }
         if(i == 9){
             printf("       (10e toujours mieux que Chelsea) ¯|_(ツ)_/¯ ");
         }
         printf("\nNOMBRE TDB: %d \n", Jeu->classementFinal[i].abattoirJoueur);
     }
     printf("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ \n");
     printf(reset);
 }
References Joueur::abattoirJoueur, BORA, Jeux::classementFinal, Jeux::nbJoueurs, Joueur::nomJoueur, and reset.
Referenced by tour2Jeu().
afficherCarte()
void afficherCarte (Carte carte, int etat)
: demande à l'utilisateur le niveau des bots
Author
: Etienne Massonnet
Date
: 14 juin 2023
Precondition
:
Postcondition
:
Definition at line 218 of file etienne.c.
{
     if(etat == CARTE_MAIN_JOUE){
         printf(BBLK"\e[1;90m""[%s / %d🐮]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
         printf(reset);
     }else{
         switch(carte.teteDeboeuf){
         case BLANC_VIOLET:
             // printf(BPUR"┌━━━━━━┐"reset"\n");
             // printf(BPUR"|"WHTHB BBLK"%s "reset BPUR"|"reset"\n",intCarteToCharCarte(carte.valeur));
             // printf(BPUR"|"WHTHB"🐮  🐮"reset BPUR"|"reset"\n");
             // printf(BPUR"|"WHTHB BBLK"  0%d  "reset BPUR"|"reset"\n",carte.teteDeboeuf);
             // printf(BPUR"┗━━━━━━┛"reset"\n");
             printf(BPUR"["WHTHB BBLK"%s "BPUR"/ "BBLK"%d🐮"reset BPUR"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
          case BLEU_CYAN:
             // printf(BBLU"┌━━━━━━┐"reset"\n");
             // printf(BBLU"|"CYAHB BBLK"%s "reset BBLU"|"reset"\n",intCarteToCharCarte(carte.valeur));
             // printf(BBLU"|"CYAHB"🐮  🐮"reset BBLU"|"reset"\n");
             // printf(BBLU"|"CYAHB BBLK"  0%d  "reset BBLU"|"reset"\n",carte.teteDeboeuf);
             // printf(BBLU"┗━━━━━━┛"reset"\n");
             printf(BBLU"["CYAHB BBLK"%s "BBLU"/ "BBLK"%d🐮"reset BBLU"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
          case VERT_JAUNE:
             // printf(BGRN"┌━━━━━━┐"reset"\n");
             // printf(BGRN"|"GRNHB BORA"%s"reset BGRN"|"reset"\n",intCarteToCharCarte(carte.valeur));
             // printf(BGRN"|"GRNHB"🐮  🐮"reset BGRN"|"reset"\n");
             // printf(BGRN"|"GRNHB BORA"  0%d  "reset BGRN"|"reset"\n",carte.teteDeboeuf);
             // printf(BGRN"┗━━━━━━┛"reset"\n");
             printf(BGRN"["GRNHB BORA"%s "BBLK"/ "BORA"%d🐮"reset BGRN"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
          case ROUGE_VERT:
             // printf(BBLU"┌━━━━━━┐"reset"\n");
             // printf(BBLU"|"REDHB BGRN"%s "reset BBLU"|"reset"\n",intCarteToCharCarte(carte.valeur));
             // printf(BBLU"|"REDHB"🐮  🐮"reset BBLU"|"reset"\n");
             // printf(BBLU"|"REDHB BGRN"  0%d  "reset BBLU"|"reset"\n",carte.teteDeboeuf);
             // printf(BBLU"┗━━━━━━┛"reset"\n");
             printf(BBLU"["REDHB BGRN"%s "BBLU"/ "BGRN"%d🐮"reset BBLU"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
          case VIOLET_ORANGE:
             // printf(BRED"┌━━━━━━┐"reset"\n");
             // printf(BRED"|"PURHB BORA"%s "reset BRED"|"reset"\n",intCarteToCharCarte(carte.valeur));
             // printf(BRED"|"PURHB"🐮  🐮"reset BRED"|"reset"\n");
             // printf(BRED"|"PURHB BORA"  0%d  "reset BRED"|"reset"\n",carte.teteDeboeuf);
             // printf(BRED"┗━━━━━━┛"reset"\n");
             printf(BRED"["PURHB BORA"%s "BRED"/ "BORA"%d🐮"reset BRED"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
         default:
             printf("[%s / %d] ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
         }
     }
 }
References BBLK, BBLU, BGRN, BLANC_VIOLET, BLEU_CYAN, BORA, BPUR, BRED, CARTE_MAIN_JOUE, CYAHB, GRNHB, intCarteToCharCarte(), PURHB, REDHB, reset, ROUGE_VERT, Carte::teteDeboeuf, Carte::valeur, VERT_JAUNE, VIOLET_ORANGE, and WHTHB.
Referenced by afficherMainJoueur(), afficherSeries(), and choixColonneJoueeHumain().
afficherMainJoueur()
void afficherMainJoueur (Joueur * joueur)
: Permet d'afficher la main du joueur
Authors
: Paul Brechenmacher & Adrien Le Mée Moret
Date
: June 12th, 2023 4:01 PM
Precondition
: Prend le pointeur Joueur, pour afficher la main du Joueur selon son état
Postcondition
: affichage de la main
Definition at line 150 of file adrien.c.
{
     for(int i = 0; i <joueur->nb_cartes ;i++){
         printf(BWHT"     %d      "reset,i+1);
     }
     printf("\n");
     for(int idCarte = 0; idCarte < joueur->nb_cartes;idCarte++){
         if(!joueur->mainJoueur[idCarte].carteJouee){
             afficherCarte(joueur->mainJoueur[idCarte],CARTE_MAIN_NONJOUE);
         }else{
             afficherCarte(joueur->mainJoueur[idCarte],CARTE_MAIN_JOUE);
         }
     }
 }
References afficherCarte(), BWHT, CARTE_MAIN_JOUE, CARTE_MAIN_NONJOUE, Carte::carteJouee, Joueur::mainJoueur, Joueur::nb_cartes, and reset.
Referenced by creationCarteJoue().
classement()
void classement (Jeux * Jeu)
Definition at line 110 of file adrien.c.
{
     int compteur = 1;
     Joueur k;
     while (compteur != 0){
         compteur = 0;
         for (int i = 0; i < Jeu->nbJoueurs-1; i++){
             if (Jeu->classementFinal[i].abattoirJoueur > Jeu->classementFinal[i+1].abattoirJoueur){
                 k = Jeu->classementFinal[i];
                 Jeu->classementFinal[i] = Jeu->classementFinal[i+1];
                 Jeu->classementFinal[i+1] = k;
                 compteur++;
             }
         }
     }
 }
References Joueur::abattoirJoueur, Jeux::classementFinal, and Jeux::nbJoueurs.
Referenced by tour2Jeu().
creationCarte()
Carte creationCarte (int valeur, int tdb)
Definition at line 19 of file adrien.c.
{
     Carte lacarte;
     lacarte.valeur = valeur;
     lacarte.teteDeboeuf = tdb;
     lacarte.carteJouee = 0;
     return lacarte;
 }
References Carte::carteJouee, Carte::teteDeboeuf, and Carte::valeur.
Referenced by creationPioche().
creationPioche()
void creationPioche (Jeux * Jeu)
Definition at line 32 of file adrien.c.
{
     FILE* cartes = NULL;
     char* mot;
     char ligne[1000];
     mot = malloc(1000 * sizeof(char));
     cartes = fopen("cartes.csv", "r");
     int valeur;
     int tdb;
     int nbLignesLues = 0;
     if (cartes == NULL){
         printf("Erreur d'ouverture du fichier \n");
     } else {
         while(fgets(ligne,1000,cartes) != NULL){
             mot = strtok(ligne,";");
             while(mot != NULL){
                 valeur = atoi(mot);
                 mot = strtok(NULL,";");
                 tdb = atoi(mot);
                 mot = strtok(NULL,";");
             }
             Jeu->pioche[nbLignesLues] = creationCarte(valeur,tdb);
             nbLignesLues++;
         }
     }
     fclose(cartes);
 }
References creationCarte(), and Jeux::pioche.
Referenced by startJeu().
placementSeries()
void placementSeries (Jeux * Jeu)
: La procédure récupère l'écart supérieu le plus petit et si la carte jouée est inférieure aux séries
Authors
: Paul Brechenmacher & Adrien Le Mée Moret
Date
: June 12th, 2023 4:01 PM
Precondition
: La procédure prend en paramètre un pointeur de Jeu, et utilise l'ordre de passage et le nbJoueurs et les séries
Postcondition
: Renvoie des séries modifiées selon les cartes jouées de chaque joueur
Definition at line 76 of file adrien.c.
{
     int maxecart = 104;
     int ecart, colonneJouee, nbCarteNegative;
     for(int idJoueur = 0; idJoueur < Jeu->nbJoueurs;idJoueur++){
         nbCarteNegative = 0;
         for(int colonne = 0; colonne < 4; colonne++){
             ecart = Jeu->ordreDePassage[idJoueur].carteJouee.valeur - Jeu->series[0][colonne].valeur;
             if (ecart < 0){
                 nbCarteNegative++;
             }else{
                 if (ecart < maxecart){
                     maxecart = ecart;
                     colonneJouee = colonne;
                 }
             }
         }
         system("clear");
         afficherJeu(*Jeu);
         #ifdef NOSLEEP
         #else
             sleep(2);
         #endif
         placementCarteSeries(Jeu,nbCarteNegative,colonneJouee,idJoueur);
         seuiltdb(Jeu,idJoueur);
         printf("Abattoir %s : %d\n",Jeu->tabJoueurs[idJoueur].nomJoueur,Jeu->tabJoueurs[idJoueur].abattoirJoueur);
     }
 }
References Joueur::abattoirJoueur, afficherJeu(), Joueur::carteJouee, Jeux::nbJoueurs, Joueur::nomJoueur, Jeux::ordreDePassage, placementCarteSeries(), Jeux::series, seuiltdb(), Jeux::tabJoueurs, and Carte::valeur.
Referenced by mancheJoueurs().
seuiltdb()
void seuiltdb (Jeux * Jeu, int idjoueur)
Definition at line 66 of file adrien.c.
{
     if(Jeu->tabJoueurs[idjoueur].abattoirJoueur >= Jeu->seuil){
         Jeu->classementFinal = malloc(Jeu->nbJoueurs * sizeof(Joueur));
         for(int i = 0; i < Jeu->nbJoueurs; i++){
             Jeu->classementFinal[i] = Jeu->tabJoueurs[i];
         }
         Jeu->etatduJeu = 0;
     }
 }
References Joueur::abattoirJoueur, Jeux::classementFinal, Jeux::etatduJeu, Jeux::nbJoueurs, Jeux::seuil, and Jeux::tabJoueurs.
Referenced by placementSeries().
supprimercarte()
void supprimercarte (Carte * cartes, int * p_taille, int position)
Definition at line 170 of file adrien.c.
{
     *p_taille = *p_taille - 1;
     while(position<*p_taille){
         cartes[position] = cartes[position+1];
         position++;
     }
 }
Referenced by creationCarteJoue().