ProjetP1: affichage.c File Reference
affichage.c File Reference
#include "affichage.h"
#include "bots.h"
#include "creation.h"
#include "jeu.h"
Functions
void affclassement (Jeux *Jeu)
: La procédure affiche le classement final des joueurs
void afficherMainJoueur (Joueur *joueur)
: Permet d'afficher la main du joueur
void afficherDraft (Jeux Jeu)
Affiche la totalité des cartes de la pioche.
void affMenu0Arg (Jeux *Jeu)
Affiche le menu demande à l'utilisateur le nombre de joueurs et de bots, leurs noms, le mode de jeu , le niveau des bots.
void affMenu2Arg (Jeux *Jeu, int argc, char *argv[])
Affiche le menu et demande à l'utilisateur le mode de jeu souhaité et le niveau des bots.
void affMenu3Arg (Jeux *Jeu, int argc, char *argv[])
affiche le menu et demande à l'utilisateur le mode de jeu souhaité et le niveau des bots
void afficherCarte (Carte carte, int etat)
Affiche une carte de manière différente en fonction de son état.
void affichageLogo ()
affiche "Le 6 qui prend" lorsque le jeu est lancé
void afficherAbattoir (Jeux Jeu)
: Permet d'afficher l'abbatoir de chaque joueur
void afficherSeries (Jeux Jeu)
: Permet d'afficher toute les series
void afficherJeu (Jeux Jeu)
: Permet d'afficher le jeu
void lancementArg (Jeux *Jeu, int argc, char *argv[])
Affiche le menu de début de jeu de plusieurs manières en fonction du nombre d'arguments utilisés.
Function Documentation
affclassement()
: affclassement (Jeux * Jeu)
: La procédure affiche le classement final des joueurs
Authors
: Adrien Le Mée Moret
Date
: 12 juin
Precondition
: La procédure prend en paramètre un pointeur de Jeux
Postcondition
: La procédure se termine avec l'affichage du dernier joueur du classement
Definition at line 6 of file affichage.c.
{
     printf(BORA);
     printf("━━━━━━━━━━━━━━━━━CLASSEMENT FINAL━━━━━━━━━━━━━━━━━ \n");
     for (int i = 0; i < Jeu->nbJoueurs; i++){
         printf("-------------------POSITION %d------------------- \n", i+1);
         printf("NOM: %s  ", Jeu->classementFinal[i].nomJoueur);
         if(i == 1){
             printf("       (dommage 2ème comme Arsenal)");
         }
         if(i == 9){
             printf("       (10e toujours mieux que Chelsea) ¯|_(ツ)_/¯ ");
         }
         printf("\nNOMBRE TDB: %d \n", Jeu->classementFinal[i].abattoirJoueur);
     }
     printf("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ \n");
     printf(reset);
 }
References Joueur::abattoirJoueur, BORA, Jeux::classementFinal, Jeux::nbJoueurs, Joueur::nomJoueur, and reset.
Referenced by tour2Jeu().
affichageLogo()
affichageLogo ()
affiche "Le 6 qui prend" lorsque le jeu est lancé
Authors
Etienne Massonnet, Paul Brechenmacher
Date
June 13th, 2023 12:04 AM
Definition at line 164 of file affichage.c.
                     {
     system("clear");
     printf(BYEL);
     printf("/ $$                        /$$$$$$                            /$$                                                     /$$ \n");
     printf("| $$                       /$$__  $$                          |__/                                                    | $$\n");
     printf("| $$        /$$$$$$       | $$  |__/        /$$$$$$  /$$   /$$ /$$        /$$$$$$   /$$$$$$   /$$$$$$  /$$$$$$$   /$$$$$$$\n");
     printf("| $$       /$$__  $$      | $$$$$$$        /$$__  $$| $$  | $$| $$       /$$__  $$ /$$__  $$ /$$__  $$| $$__  $$ /$$__  $$\n");
     printf("| $$      | $$$$$$$$      | $$__  $$      | $$  | $$| $$  | $$| $$      | $$  | $$| $$  |__/| $$$$$$$$| $$  | $$| $$  | $$\n");
     printf("| $$      | $$_____/      | $$  | $$      | $$  | $$| $$  | $$| $$      | $$  | $$| $$      | $$_____/| $$  | $$| $$  | $$\n");
     printf("| $$$$$$$$|  $$$$$$$      |  $$$$$$/      |  $$$$$$$|  $$$$$$/| $$      | $$$$$$$/| $$      |  $$$$$$$| $$  | $$|  $$$$$$$\n");
     printf("|________/ |_______/       |______/        |____  $$ |______/ |__/      | $$____/ |__/       |_______/|__/  |__/ |_______/\n");
     printf("                                                | $$                    | $$                                              \n");
     printf("                                                | $$                    | $$                                              \n");
     printf("                                                |__/                    |__/                                              \n");
     printf(reset);
 }
References BYEL, and reset.
Referenced by startJeu().
afficherAbattoir()
: afficherAbattoir (Jeux Jeu)
: Permet d'afficher l'abbatoir de chaque joueur
Author
: Goncalves Nathan
Date
: 18/06/2223
Precondition
: Prend la stucture Jeu, pour afficher l'entièreté de l'abbatoir
Postcondition
: Affichage de l'abbatoir
Definition at line 181 of file affichage.c.
{
    printf(BRED);
     printf("━━━━━━━━━━━━━RECAP FIN DE MANCHE━━━━━━━━━━━━━━━━ \n");
     for (int i = 0; i < Jeu.nbJoueurs; i++){
         printf("-------------------JOUEUR %d------------------- \n", i+1);
         printf("NOM: %s  ", Jeu.tabJoueurs[i].nomJoueur);
         printf("\nNOMBRE TDB: %d \n", Jeu.tabJoueurs[i].abattoirJoueur);
     }
     printf("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ \n");
     printf(reset);
 }
References Joueur::abattoirJoueur, BRED, Jeux::nbJoueurs, Joueur::nomJoueur, reset, and Jeux::tabJoueurs.
Referenced by mancheJoueurs().
afficherCarte()
afficherCarte (Carte carte, int etat)
Affiche une carte de manière différente en fonction de son état.
Authors
Etienne Massonnet, Paul Brechenmacher
Date
June 12th, 2023 6:30 PM
Precondition
Prend en paramètre une carte et son état (défini par l'énumération etat)
Postcondition
La carte est affichée d'une couleur différente en fonction de sa valeur, comme dicté par les règles du jeu
Definition at line 122 of file affichage.c.
{
     if(etat == CARTE_MAIN_JOUE){
         // Si la carte a déjà été jouée, elle est affichée en noir
         printf(BBLK"\e[1;90m""[%s / %d🐮]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
         printf(reset);
     }else{
         /* Sinon, elle est affichée d'une couleur différente en fonction de son nombre de TDB :
         - 1 TDB : Blanche
         - 2 TDB : Bleue
         - 3 TDB : Verte
         - 5 TDB : Rouge
         - 7 TDB : Rose
         */
         switch(carte.teteDeboeuf){
         case BLANC_VIOLET:
             printf(BPUR"["WHTHB BBLK"%s "BPUR"/ "BBLK"%d🐮"reset BPUR"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
          case BLEU_CYAN:
             printf(BBLU"["CYAHB BBLK"%s "BBLU"/ "BBLK"%d🐮"reset BBLU"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
          case VERT_JAUNE:
             printf(BGRN"["GRNHB BORA"%s "BBLK"/ "BORA"%d🐮"reset BGRN"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
          case ROUGE_VERT:
             printf(BBLU"["REDHB BGRN"%s "BBLU"/ "BGRN"%d🐮"reset BBLU"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
          case VIOLET_ORANGE:
             printf(BRED"["PURHB BORA"%s "BRED"/ "BORA"%d🐮"reset BRED"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
         default:
             printf("[%s / %d] ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
         }
     }
 }
References BBLK, BBLU, BGRN, BLANC_VIOLET, BLEU_CYAN, BORA, BPUR, BRED, CARTE_MAIN_JOUE, CYAHB, GRNHB, intCarteToCharCarte(), PURHB, REDHB, reset, ROUGE_VERT, Carte::teteDeboeuf, Carte::valeur, VERT_JAUNE, VIOLET_ORANGE, and WHTHB.
Referenced by afficherDraft(), afficherMainJoueur(), afficherSeries(), and choixColonneJoueeHumain().
afficherDraft()
afficherDraft (Jeux Jeu)
Affiche la totalité des cartes de la pioche.
Authors
Etienne Massonnet, Nathan Goncalves
Date
June 18th, 2023 23:35 PM
Precondition
Prend en argument le jeu
Postcondition
Affiche dans le terminal toutes les cartes de la pioche, par lignes de 10 et dans l'ordre croissant
Definition at line 38 of file affichage.c.
{
     printf("\n");
     // On affiche les 100 premières cartes par lignes de 10
     for(int j=0; j<10; j++){
         for (int i=j*10; i<j*10+10; i++){
             if (Jeu.pioche[i].carteDraft){
                 afficherCarte(Jeu.pioche[i], 1);
             }else{
                 afficherCarte(Jeu.pioche[i], 0);
             }
         }
         printf("\n\n");
     }
     // On affiche les 4 dernières cartes
     for(int k=100; k<104; k++){
         if (Jeu.pioche[k].carteDraft){
             afficherCarte(Jeu.pioche[k], 1);
         }else{
             afficherCarte(Jeu.pioche[k], 0);
         }
     }
     printf("\n\n");
 }
References afficherCarte(), Carte::carteDraft, and Jeux::pioche.
Referenced by choixCartesDraft(), and distributionPiocheDraft().
afficherJeu()
: afficherJeu (Jeux Jeu)
: Permet d'afficher le jeu
Authors
: Paul Brechenmacher & Etienne Massonnet & Nathan Goncalves
Date
: June 12th, 2023 4:01 PM
Precondition
: Prend le jeu pour accéder à ses données
Postcondition
: Le jeu est affiché
Definition at line 215 of file affichage.c.
{
     afficherSeries(Jeu);
 }
References afficherSeries().
Referenced by choixColonneJoueeHumain(), creationCarteJoue(), mancheJoueurs(), and placementSeries().
afficherMainJoueur()
: afficherMainJoueur (Joueur * joueur)
: Permet d'afficher la main du joueur
Authors
: Paul Brechenmacher & Adrien Le Mée Moret
Date
: June 12th, 2023 4:01 PM
Precondition
: Prend le pointeur Joueur, pour afficher la main du Joueur selon son état
Postcondition
: affichage de la main
Definition at line 24 of file affichage.c.
{
     for(int i = 0; i <joueur->nb_cartes ;i++){
         printf(BWHT"     %d      "reset,i+1);
     }
     printf("\n");
     for(int idCarte = 0; idCarte < joueur->nb_cartes;idCarte++){
         if(!joueur->mainJoueur[idCarte].carteJouee){
             afficherCarte(joueur->mainJoueur[idCarte],CARTE_MAIN_NONJOUE);
         }else{
             afficherCarte(joueur->mainJoueur[idCarte],CARTE_MAIN_JOUE);
         }
     }
 }
References afficherCarte(), BWHT, CARTE_MAIN_JOUE, CARTE_MAIN_NONJOUE, Carte::carteJouee, Joueur::mainJoueur, Joueur::nb_cartes, and reset.
Referenced by creationCarteJoue().
afficherSeries()
: afficherSeries (Jeux Jeu)
: Permet d'afficher toute les series
Authors
: Nathan Goncalves & Paul Brechenmacher
Date
: 05/06/2223
Precondition
: Prend la stucture Jeu, pour afficher l'entièreté des series
Postcondition
: Affichage des series
Definition at line 195 of file affichage.c.
{
     Carte NeutreCarte;
     NeutreCarte.teteDeboeuf = 0;
     NeutreCarte.valeur = 0;
     for(int l = 0; l < 5 ; l++){
         for(int c =0; c < 4; c++){
             if (Jeu.series[l][c].valeur != NeutreCarte.valeur && Jeu.series[l][c].teteDeboeuf != NeutreCarte.teteDeboeuf){
                 afficherCarte(Jeu.series[l][c],CARTE_SERIES);
             }else{
                 printf("            ");
             }
         }
         printf("\n");
     }
     printf("\n");
 }
References afficherCarte(), CARTE_SERIES, Jeux::series, Carte::teteDeboeuf, and Carte::valeur.
Referenced by afficherJeu().
affMenu0Arg()
affMenu0Arg (Jeux * Jeu)
Affiche le menu demande à l'utilisateur le nombre de joueurs et de bots, leurs noms, le mode de jeu , le niveau des bots.
Author
Etienne Massonnet
Date
May 29th, 2023 5:33 PM
Precondition
Prend en paramètre le jeu complet
Postcondition
Affiche le menu et stocke dans des variables les réponses de l'utilisateur, initialise le tableau de joueurs grâce à creationTabJoueur
Definition at line 62 of file affichage.c.
{
     int nbJoueurs,nbHumains,nbBots;
     printf(BWHT"\n┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ Bienvenue ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n\n");
     printf("\nEntrez le nombre souhaité de joueurs au total ("BGRN"humains "BWHT"ou "BRED"bots"BWHT") entre 2 et 10 inclus : ");
     scanf("%d", &nbJoueurs);
     // Sécurité en cas de saisie invalide
     while (nbJoueurs>10 || nbJoueurs<2){
         emptyBuffer();
         printf(BRED"\n /!\\ Erreur de saisie : entrez un nombre entier entre 2 et 10 inclus : "BWHT);
         scanf("%d", &nbJoueurs);
     }
     printf("Parmi ces %d joueurs, combien y a-t-il d'humains ? : ", nbJoueurs);
     scanf("%d", &nbHumains);
     // Sécurité en cas de saisie invalide
     while (nbHumains<0 || nbHumains>nbJoueurs){
         emptyBuffer();
         printf(BRED"\n /!\\ Erreur de saisie : entrez un nombre entier entre 0 et %d inclus : "reset, nbJoueurs);
         scanf("%d", &nbHumains);
     }
     nbBots=nbJoueurs-nbHumains;
     creationTabJoueur(Jeu,nbHumains,nbJoueurs,nbBots);
     demandeVariante(Jeu);
     if (nbBots>0){
         demandeNivBots(Jeu);
     }
 }
References BGRN, BRED, BWHT, creationTabJoueur(), demandeNivBots(), demandeVariante(), emptyBuffer(), and reset.
Referenced by lancementArg().
affMenu2Arg()
affMenu2Arg (Jeux * Jeu, int argc, char * argv[])
Affiche le menu et demande à l'utilisateur le mode de jeu souhaité et le niveau des bots.
Author
Etienne Massonnet
Date
May 29th, 2023 5:33 PM
Precondition
Prend en paramètre le pointeur Jeu, ainsi que les arguments
Postcondition
Affiche le menu et stocke dans des variables les réponses de l'utilisateur, initialise le tableau de joueurs grâce à creationTabJoueur
Definition at line 91 of file affichage.c.
{
     printf(BWHT"\n┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ Bienvenue ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n\n");
     int nbBots=atoi(argv[1]);
     int nbHumains=atoi(argv[2]);
     int nbJoueurs=nbBots+nbHumains;
     printf("\nVous avez choisi de jouer avec %d bots et %d humains\n"reset,nbBots,nbHumains);
     creationTabJoueur(Jeu,nbHumains,nbJoueurs,nbBots);
     demandeVariante(Jeu);
     if (nbBots>0){
         demandeNivBots(Jeu);
     }
 }
References BWHT, creationTabJoueur(), demandeNivBots(), demandeVariante(), and reset.
Referenced by lancementArg().
affMenu3Arg()
affMenu3Arg (Jeux * Jeu, int argc, char * argv[])
affiche le menu et demande à l'utilisateur le mode de jeu souhaité et le niveau des bots
Author
Etienne Massonnet
Date
May 29th, 2023 5:33 PM
Precondition
Prend en paramètre le pointeur Jeu, ainsi que les arguments
Postcondition
Affiche le menu et stocke dans des variables les réponses de l'utilisateur, initialise le tableau de joueurs grâce à creationTabJoueur
Definition at line 106 of file affichage.c.
{
     printf(BWHT"\n┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ Bienvenue ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n\n");
     int nbBots=atoi(argv[1]);
     int nbHumains=atoi(argv[2]);
     int nbJoueurs=nbBots+nbHumains;
     Jeu->seuil = atoi(argv[3]);
     printf("\nVous avez choisi de jouer avec %d bots et %d humains, avec un seuil de %d têtes de boeuf.\n"reset,nbBots,nbHumains,Jeu->seuil );
     creationTabJoueur(Jeu,nbHumains,nbJoueurs,nbBots);
     demandeVariante(Jeu);
     if (nbBots>0){
         demandeNivBots(Jeu);
     }
 }
References BWHT, creationTabJoueur(), demandeNivBots(), demandeVariante(), reset, and Jeux::seuil.
Referenced by lancementArg().
lancementArg()
lancementArg (Jeux * Jeu, int argc, char * argv[])
Affiche le menu de début de jeu de plusieurs manières en fonction du nombre d'arguments utilisés.
Author
Etienne Massonnet
Date
June 12th, 2023 2:27 PM
Precondition
Prend le pointeur Jeu, le nombre d'arguments entrés et les arguments en question
Postcondition
Le menu est affiché de manière adaptée aux arguments
Definition at line 221 of file affichage.c.
{
     // Vérification des arguments entrés
     Jeu->seuil = 66;
     if(argc>1){
         if(argc==2){
             printf(BRED"\n/!\\ ERREUR : Si vous souhaitez utiliser des arguments, choisissez deux entiers dont la somme est comprise entre 2 et 10.\n             Un troisième argument (entier naturel à partir de 2) peut être entré pour choisir le seuil de têtes de boeuf entraînant la fin de la partie.\n\n"reset);
             exit(EXIT_SUCCESS);
         }else{
             if(argc==4){
                 if(atoi(argv[3])<2){
                     printf(BRED"\n/!\\ ERREUR : On vous encourage à mettre plus que 1 TDB comme seuil sinon c'est moins drôle\n\n"reset);
                     exit(EXIT_SUCCESS);
                 }
             }
             int total = atoi(argv[1])+atoi(argv[2]);
             if( (total < 2 || total >10) || argc > 4){
                 printf(BRED"\n/!\\ ERREUR : Si vous souhaitez utiliser des arguments, choisissez deux entiers dont la somme est comprise entre 2 et 10.\n             Un troisième argument (entier naturel à partir de 2) peut être entré pour choisir le seuil de têtes de boeuf entraînant la fin de la partie.\n\n"reset);
                 exit(EXIT_SUCCESS);
             }
         }
     }
     // Lancement de menu différent selon les arguments
     switch(argc){
         case 1 :
                 affMenu0Arg(Jeu);
                 break;
         case 3 :
                 affMenu2Arg(Jeu, argc, argv);
                 break;
         case 4 :
                 affMenu3Arg(Jeu, argc, argv);
                 break;
         default :
                 break;
     }
 }
References affMenu0Arg(), affMenu2Arg(), affMenu3Arg(), BRED, reset, and Jeux::seuil.
Referenced by startJeu().