ProjetP1: bots.h File Reference
bots.h File Reference
#include "structure.h"
Functions
int choixColonneJoueeBotHard (Jeux *Jeu)
Permet de choisir la colonne pour le Bot de difficulté Hard
int choixColonneJoueeBotFacile (Jeux *Jeu)
Le bot facile choisit la colonne avec le plus haut nombre de têtes de boeuf.
void creationCarteJoueBot (Jeux *Jeu, int idBot)
Choisit la carte à jouer du Bot selon la difficulté
void demandeNivBots (Jeux *Jeu)
Demande à l'utilisateur le niveau des bots.
void choixCarteEasy (Jeux *Jeu, int idBot)
Permet au bot easy de choisir une carte.
void choixCarteMedium (Jeux *Jeu, int idBot)
Permet au bot medium de choisir une carte a jouer.
void choixCarteHard (Jeux *Jeu, int idBot)
Détermine la carte que choisit le bot de niveau difficile.
Function Documentation
choixCarteEasy()
void choixCarteEasy (Jeux * Jeu, int idBot)
Permet au bot easy de choisir une carte.
choixCarteEasy(Jeux* Jeu, int idBot)
Authors
Nathan Goncalves & Paul Brechenmacher & Etienne Massonnet
Date
19/06/2223
Precondition
Prend la stucture Jeu et l'id du bot, pour que le bot easy choisisse une carte
Postcondition
le bot easy choisi une carte
Definition at line 45 of file bots.c.
{
     int ecartValeur,choixCarte;
     int maxEcartValeur = 0;
     for(int idCarteMain = 0; idCarteMain < 10; idCarteMain++){
         /*Si la carte n'a pas était joué*/
         if(!Jeu->tabJoueurs[idBot].mainJoueur[idCarteMain].carteJouee){
             for(int idCarteSeries = 0; idCarteSeries < 4; idCarteSeries++){
                 /* Calcule l'écart entre chaque carte de la main du joueur et chaque 1ère carte des séries*/
                 ecartValeur = Jeu->tabJoueurs[idBot].mainJoueur[idCarteMain].valeur - Jeu->series[0][idCarteSeries].valeur;
                 if(ecartValeur > 0){
                     if(ecartValeur > maxEcartValeur){
                         maxEcartValeur = ecartValeur;
                         choixCarte = idCarteMain;
                     }
                 }
             }
         }
     }
     Jeu->tabJoueurs[idBot].carteJouee = Jeu->tabJoueurs[idBot].mainJoueur[choixCarte];
     Jeu->tabJoueurs[idBot].carteJouee.carteJouee = 1;
 }
References Carte::carteJouee, Joueur::carteJouee, Joueur::mainJoueur, Jeux::series, Jeux::tabJoueurs, and Carte::valeur.
Referenced by creationCarteJoueBot().
choixCarteHard()
void choixCarteHard (Jeux * Jeu, int idBot)
Détermine la carte que choisit le bot de niveau difficile.
Authors
Etienne Massonnet, Nathan Goncalves
Date
June 17th, 2023 12:15 AM
Precondition
Prend en argument le pointeur Jeu et l'id du bot concerné
Postcondition
La carte choisie par le bot est celle qui a le plus petit écart avec l'une des séries
Definition at line 20 of file bots.c.
{
     // Détermine la carte ayant le plus petit écart avec la 1ère carte d'une des séries
     int ecartValeur,choixCarte;
     int minEcartValeur = 105;
     for(int idCarteMain = 0; idCarteMain < 10; idCarteMain++){
         // On vérifie que la carte n'a pas été jouée
         if(!Jeu->tabJoueurs[idBot].mainJoueur[idCarteMain].carteJouee){
             for(int idCarteSeries = 0; idCarteSeries < 4; idCarteSeries++){
                 // Calcule l'écart entre chaque carte de la main du bot et chaque 1ère carte des séries
                 ecartValeur = Jeu->tabJoueurs[idBot].mainJoueur[idCarteMain].valeur - Jeu->series[0][idCarteSeries].valeur;
                 if(ecartValeur > 0){
                     if(ecartValeur < minEcartValeur){
                         minEcartValeur = ecartValeur;
                         choixCarte = idCarteMain;
                     }
                 }
             }
         }
     }
     // On met à jour la carte jouée et on met à jour son statut pour éviter qu'elle soit jouée une 2ème fois
     Jeu->tabJoueurs[idBot].carteJouee = Jeu->tabJoueurs[idBot].mainJoueur[choixCarte];
     Jeu->tabJoueurs[idBot].carteJouee.carteJouee = 1;
 }
References Carte::carteJouee, Joueur::carteJouee, Joueur::mainJoueur, Jeux::series, Jeux::tabJoueurs, and Carte::valeur.
Referenced by creationCarteJoueBot().
choixCarteMedium()
void choixCarteMedium (Jeux * Jeu, int idBot)
Permet au bot medium de choisir une carte a jouer.
Authors
Nathan Goncalves & Paul Brechenmacher & Etienne Massonnet
Date
19/06/2223
Precondition
Prend la stucture Jeu et l'id du bot, pour que le bot medium choisisse une carte
Postcondition
le bot medium choisi une carte aleatoirement
Definition at line 72 of file bots.c.
{
      int choixCarte;
     do{
         choixCarte = (rand() % 10);
         Jeu->tabJoueurs[idBot].carteJouee = Jeu->tabJoueurs[idBot].mainJoueur[choixCarte];
     }while(Jeu->tabJoueurs[idBot].mainJoueur[choixCarte].carteJouee);
     Jeu->tabJoueurs[idBot].carteJouee.carteJouee = 1;
 }
References Carte::carteJouee, Joueur::carteJouee, Joueur::mainJoueur, and Jeux::tabJoueurs.
Referenced by creationCarteJoueBot().
choixColonneJoueeBotFacile()
int choixColonneJoueeBotFacile (Jeux * Jeu)
Le bot facile choisit la colonne avec le plus haut nombre de têtes de boeuf.
Author
Paul Brechenmacher
Date
14 Juin 2023
Precondition
Prend le pointeur Jeu, pour les séries
Postcondition
Renvoie un entier colonneJouee
Definition at line 99 of file bots.c.
{
     int colonneJouee,nbBoeuf;
     int nbMaxBoeuf = 0;
     for(int idColonne = 0; idColonne < 4; idColonne++){
         nbBoeuf = 0;
         for(int idLigne = 0; idLigne < 5; idLigne++){
             nbBoeuf = nbBoeuf + Jeu->series[idLigne][idColonne].teteDeboeuf;
         }
         if(nbBoeuf > nbMaxBoeuf){
             nbMaxBoeuf = nbBoeuf;
             colonneJouee = idColonne;
         }
     }
     return colonneJouee;
 }
References Jeux::series, and Carte::teteDeboeuf.
Referenced by choixColonneJouee().
choixColonneJoueeBotHard()
int choixColonneJoueeBotHard (Jeux * Jeu)
Permet de choisir la colonne pour le Bot de difficulté Hard
Author
Paul Brechenmacher
Date
14 Juin 2023
Precondition
Prend le pointeur Jeu, pour les séries
Postcondition
Renvoie un entier colonneJouee
Definition at line 82 of file bots.c.
{
     int colonneJouee,nbBoeuf;
     int nbMinBoeuf = 100;
     for(int idColonne = 0; idColonne < 4; idColonne++){
         nbBoeuf = 0;
         for(int idLigne = 0; idLigne < 5; idLigne++){
             nbBoeuf = nbBoeuf + Jeu->series[idLigne][idColonne].teteDeboeuf;
         }
         if(nbBoeuf < nbMinBoeuf){
             nbMinBoeuf = nbBoeuf;
             colonneJouee = idColonne;
         }
     }
     return colonneJouee;
 }
References Jeux::series, and Carte::teteDeboeuf.
Referenced by choixColonneJouee().
creationCarteJoueBot()
creationCarteJoueBot (Jeux * Jeu, int idBot)
Choisit la carte à jouer du Bot selon la difficulté
Author
Paul Brechenmacher
Date
June 14th, 2023 9:17 PM
Precondition
Pointeur Jeu et id dans le tabJoueur
Postcondition
carteJouee sélectioné du joueur Bot.
Definition at line 49 of file creation.c.
{
     switch (Jeu->niveauBots)
     {
     case EASY:
         choixCarteEasy(Jeu,idBot);
         break;
     case MEDIUM:
         choixCarteMedium(Jeu,idBot);
         break;
     case HARD:
         choixCarteHard(Jeu,idBot);
         break;
     default:
         printf("ERREUR DE DIFFICULTÉ\n");
         break;
     }
 }
References choixCarteEasy(), choixCarteHard(), choixCarteMedium(), EASY, HARD, MEDIUM, and Jeux::niveauBots.
Referenced by creationCarteJoue().
demandeNivBots()
void demandeNivBots (Jeux * Jeu)
Demande à l'utilisateur le niveau des bots.
Author
Etienne Massonnet
Date
June 13th, 2023 4:23 PM
Precondition
Prend le pointeur Jeu pour modifier la valeur Jeu->niveauBots
Postcondition
La valeur Jeu->niveauBots est mise à jour
Definition at line 6 of file bots.c.
{
     int niveau;
     printf(BWHT"\nDifficulté des bots :\n"reset);
     printf(BGRN"> Niveau 1 : Facile\n"BORA"> Niveau 2 : Moyen\n"BRED"> Niveau 3 : Difficile\n\n"BWHT"Choisissez un niveau (1/2/3): "reset);
     scanf("%d", &niveau);
     // Sécurité en cas de saisie invalide
     while(niveau<1 || niveau >3){
         emptyBuffer();
         printf(BRED"\n /!\\ Erreur de saisie : entrez un nombre entier entre 1 et 3 inclus : "reset);
         scanf("%d", &niveau);
     }
     Jeu->niveauBots=niveau-1;
 }
References BGRN, BORA, BRED, BWHT, emptyBuffer(), Jeux::niveauBots, and reset.
Referenced by affMenu0Arg(), affMenu2Arg(), and affMenu3Arg().