ProjetP1: creation.c File Reference
creation.c File Reference
#include "affichage.h"
#include "bots.h"
#include "creation.h"
#include "jeu.h"
Functions
void creationTabJoueur (Jeux *Jeu, int nbHumains, int nbJoueurs, int nbBots)
Création d'un tableau de joueurs avec leurs infos respectives.
void creationSeriesDraft (Jeux *Jeu)
Constitue les séries.
void creationCarteJoueBot (Jeux *Jeu, int idBot)
Choisit la carte à jouer du Bot selon la difficulté
void creationCarteJoue (Jeux *Jeu)
Permet selon le type(bot/humain) de joueur d'attribuer une carte Jouée.
void creationOrdrePassage (Jeux *Jeu)
Permet selon la création d'un tableau de joueur OrdrePassage selon sa carte jouée.
void creationSeries (Jeux *Jeu)
Permet de crée les series.
void choixCartesDraft (Jeux *Jeu)
Fait choisir aux joueurs leurs 10 cartes, une par une, parmi la pioche.
void creationJoueur (Jeux *Jeu, int id, int type, char *nomJoueur)
Permet de crée les joueurs.
void initialiserOrdrePassage (Jeux *Jeu)
Permet d'initialiser un tableau de joueur OrdrePassage.
Carte creationCarte (int valeur, int tdb)
La fonction crée une carte.
void creationPioche (Jeux *Jeu)
La procédure crée les cartes du Jeu.
Function Documentation
choixCartesDraft()
choixCartesDraft (Jeux * Jeu)
Fait choisir aux joueurs leurs 10 cartes, une par une, parmi la pioche.
Authors
Etienne Massonnet, Nathan Goncalves
Date
June 18th, 2023 23:35 PM
Precondition
Prend en argument le pointeur Jeu
Postcondition
Constitue les mains des joueurs selon leurs choix, prend des cartes au hasard pour les bots
Definition at line 135 of file creation.c.
{
     int choixCarte;
     for(int i=0; i<10; i++){
         for(int idjoueur=0; idjoueur<Jeu->nbJoueurs; idjoueur++){
             if(Jeu->tabJoueurs[idjoueur].type){
                 system("clear");
                 // Sécurité en cas de saisie invalide
                 do{
                     afficherDraft(*Jeu);
                     printf(BWHT"\e[4;37m" "Choix de %s :"reset,Jeu->tabJoueurs[idjoueur].nomJoueur);
                     printf(BWHT"\nChoisissez une carte entre 1 et 104 : "reset);
                     scanf("%d", &choixCarte);
                     emptyBuffer();
                     system("clear");
                 }while(choixCarte<0 || choixCarte>104 || Jeu->pioche[choixCarte-1].carteDraft);
                 if(choixCarte == 1){
                     printf(BPUR"Bravo vous venez de drafter Victor Wembanyama <3\n"reset);
                     sleep(2);
                 }
             }else{
                 // On teste des cartes à prendre pour le bot jusqu'à en trouver une qui ne soit pas encore choisie
                 do{
                     choixCarte = (rand() % 104)+1;
                 }while(Jeu->pioche[choixCarte-1].carteDraft);
             }
             // La carte choisie est ajoutée à la main du joueur et son statut est modifié pour éviter de la choisir à nouveau
             Jeu->tabJoueurs[idjoueur].mainJoueur[i]=Jeu->pioche[choixCarte-1];
             Jeu->pioche[choixCarte-1].carteDraft=1;
         }
     }
 }
References afficherDraft(), BPUR, BWHT, Carte::carteDraft, emptyBuffer(), Joueur::mainJoueur, Jeux::nbJoueurs, Joueur::nomJoueur, Jeux::pioche, reset, Jeux::tabJoueurs, and Joueur::type.
Referenced by distributionPiocheDraft().
creationCarte()
creationCarte (int valeur, int tdb)
La fonction crée une carte.
Authors
Adrien Le Mée Moret
Date
27 mai
Precondition
La fonction prend en paramètres la valeur de la carte puis le nombre de tête de bœuf
Postcondition
La fonction retourne une carte
Definition at line 186 of file creation.c.
{
     Carte lacarte;
     lacarte.valeur = valeur;
     lacarte.teteDeboeuf = tdb;
     lacarte.carteJouee = 0;
     lacarte.carteDraft = 0;
     return lacarte;
 }
References Carte::carteDraft, Carte::carteJouee, Carte::teteDeboeuf, and Carte::valeur.
Referenced by creationPioche().
creationCarteJoue()
creationCarteJoue (Jeux * Jeu)
Permet selon le type(bot/humain) de joueur d'attribuer une carte Jouée.
Author
Paul Brechenmacher
Date
31 mai
Precondition
Prend le pointeur Jeu, pour prendre la Jeu.tabjoueur[id].type/.nomJoueur et
Postcondition
Jeu.tabjoueur[id].carteJouee modifié ainsi que l'état de la carteJouée dans la main
Definition at line 69 of file creation.c.
{
     //int nbTours = Jeu->nbTours;
     int choixCarte = 0;
     //char input[100];
     for(int idjoueur = 0; idjoueur < Jeu->nbJoueurs; idjoueur++){
         if(Jeu->tabJoueurs[idjoueur].type){
             system("clear");
             do{
                 afficherJeu(*Jeu);
                 printf(BWHT"\e[4;37m" "Main de %s :\n\n"reset,Jeu->tabJoueurs[idjoueur].nomJoueur);
                 afficherMainJoueur(&Jeu->tabJoueurs[idjoueur]);
                 printf(BWHT"\n\nChoisissez une carte entre 1 et %d :\n"reset,Jeu->tabJoueurs[idjoueur].nb_cartes);
                 scanf("%d", &choixCarte);
                 emptyBuffer();
                 system("clear");
             }while(Jeu->tabJoueurs[idjoueur].mainJoueur[choixCarte-1].carteJouee || choixCarte < 1 || choixCarte > Jeu->tabJoueurs[idjoueur].nb_cartes);
         }else{
             creationCarteJoueBot(Jeu,idjoueur);
         }
         Jeu->tabJoueurs[idjoueur].carteJouee = Jeu->tabJoueurs[idjoueur].mainJoueur[choixCarte-1];
         Jeu->tabJoueurs[idjoueur].mainJoueur[choixCarte-1].carteJouee = 1;
         supprimercarte(Jeu->tabJoueurs[idjoueur].mainJoueur, &Jeu->tabJoueurs[idjoueur].nb_cartes, choixCarte-1);
     }
 }
References afficherJeu(), afficherMainJoueur(), BWHT, Carte::carteJouee, Joueur::carteJouee, creationCarteJoueBot(), emptyBuffer(), Joueur::mainJoueur, Joueur::nb_cartes, Jeux::nbJoueurs, Joueur::nomJoueur, reset, supprimercarte(), Jeux::tabJoueurs, and Joueur::type.
Referenced by creationOrdrePassage().
creationCarteJoueBot()
void creationCarteJoueBot (Jeux * Jeu, int idBot)
Choisit la carte à jouer du Bot selon la difficulté
Author
Paul Brechenmacher
Date
June 14th, 2023 9:17 PM
Precondition
Pointeur Jeu et id dans le tabJoueur
Postcondition
carteJouee sélectioné du joueur Bot.
Definition at line 49 of file creation.c.
{
     switch (Jeu->niveauBots)
     {
     case EASY:
         choixCarteEasy(Jeu,idBot);
         break;
     case MEDIUM:
         choixCarteMedium(Jeu,idBot);
         break;
     case HARD:
         choixCarteHard(Jeu,idBot);
         break;
     default:
         printf("ERREUR DE DIFFICULTÉ\n");
         break;
     }
 }
References choixCarteEasy(), choixCarteHard(), choixCarteMedium(), EASY, HARD, MEDIUM, and Jeux::niveauBots.
Referenced by creationCarteJoue().
creationJoueur()
creationJoueur (Jeux * Jeu, int id, int type, char * nomJoueur)
Permet de crée les joueurs.
Author
Nathan Goncalves
Date
30/05/2223
Precondition
Prend la stucture Jeu,l'id et le nom du joueur pour crée l'entièreté des joueurs
Postcondition
creation des joueurs
Definition at line 169 of file creation.c.
{
     Jeu->tabJoueurs[id].nomJoueur = malloc(TAILLEMAX*sizeof(char));
     Jeu->tabJoueurs[id].mainJoueur = malloc(10*sizeof(Carte));
     Jeu->tabJoueurs[id].id = id;
     Jeu->tabJoueurs[id].type = type;
     Jeu->tabJoueurs[id].nomJoueur = nomJoueur;
 }
References Joueur::id, Joueur::mainJoueur, Joueur::nomJoueur, Jeux::tabJoueurs, TAILLEMAX, and Joueur::type.
Referenced by creationTabJoueur().
creationOrdrePassage()
creationOrdrePassage (Jeux * Jeu)
Permet selon la création d'un tableau de joueur OrdrePassage selon sa carte jouée.
Author
Paul Brechenmacher
Date
31 mai
Precondition
Prend le pointeur Jeu, pour prendre la Jeu.tabjoueur et l'ordre de passage
Postcondition
Jeu.ordreDePassage modifié selon les mains des joueurs
Definition at line 94 of file creation.c.
{
     creationCarteJoue(Jeu);
     for(int idjoueur = 0; idjoueur < Jeu->nbJoueurs; idjoueur++){
         Jeu->ordreDePassage[idjoueur] = Jeu->tabJoueurs[idjoueur] ;
     }
     Joueur tempJoueur;
     int eltEncours;
     for(int i=1; i < Jeu->nbJoueurs; i++){
         eltEncours = i;
         while(Jeu->ordreDePassage[eltEncours].carteJouee.valeur < Jeu->ordreDePassage[eltEncours-1].carteJouee.valeur && eltEncours > 0){
             tempJoueur =  Jeu->ordreDePassage[eltEncours];
             Jeu->ordreDePassage[eltEncours] = Jeu->ordreDePassage[eltEncours-1];
             Jeu->ordreDePassage[eltEncours-1] = tempJoueur;
             eltEncours--;
         }
     }
 }
References Joueur::carteJouee, creationCarteJoue(), Jeux::nbJoueurs, Jeux::ordreDePassage, Jeux::tabJoueurs, and Carte::valeur.
Referenced by mancheJoueurs().
creationPioche()
creationPioche (Jeux * Jeu)
La procédure crée les cartes du Jeu.
Authors
Adrien Le Mée Moret
Date
27 mai
Precondition
La procédure prend en paramètre un pointeur de Jeux
Postcondition
La procédure crée la pioche
Definition at line 195 of file creation.c.
{
     FILE* cartes = NULL;
     char* mot;
     char ligne[1000];
     mot = malloc(1000 * sizeof(char));
     cartes = fopen("cartes.csv", "r");
     int valeur;
     int tdb;
     int nbLignesLues = 0;
     if (cartes == NULL){
         printf("Erreur d'ouverture du fichier \n");
     } else {
         while(fgets(ligne,1000,cartes) != NULL){
             mot = strtok(ligne,";");
             while(mot != NULL){
                 valeur = atoi(mot);
                 mot = strtok(NULL,";");
                 tdb = atoi(mot);
                 mot = strtok(NULL,";");
             }
             Jeu->pioche[nbLignesLues] = creationCarte(valeur,tdb);
             nbLignesLues++;
         }
     }
     fclose(cartes);
 }
References creationCarte(), and Jeux::pioche.
Referenced by startJeu().
creationSeries()
creationSeries (Jeux * Jeu)
Permet de crée les series.
Authors
Nathan Goncalves & Paul Brechenmacher
Date
05/06/2223
Precondition
Prend la stucture Jeu, pour crée l'entièreté des series
Postcondition
création des series
Definition at line 114 of file creation.c.
{
     int carteUsed;
     Carte NeutreCarte;
     NeutreCarte.teteDeboeuf = 0;
     NeutreCarte.valeur = 0;
     // Initialisation //
     for(int l = 0; l < 5 ; l++){
         for(int c =0; c < 4; c++){
             Jeu->series[l][c] = NeutreCarte;
         }
     }
     //Création premières cartes des séries//
     carteUsed = (Jeu->nbJoueurs) * 10;
     int idCarte = 0;
     for(int idCarteUsed = carteUsed; idCarteUsed < carteUsed + 4;idCarteUsed++){
         Jeu->series[0][idCarte] = Jeu->pioche[idCarteUsed];
         idCarte++;
     }
 }
References Jeux::nbJoueurs, Jeux::pioche, Jeux::series, Carte::teteDeboeuf, and Carte::valeur.
Referenced by tour2Jeu().
creationSeriesDraft()
creationSeriesDraft (Jeux * Jeu)
Constitue les séries.
Authors
Etienne Massonnet, Nathan Goncalves
Date
June 18th, 2023 23:35 PM
Precondition
Prend en argument le pointeur Jeu
Postcondition
Constitue les séries au hasard, à partir des cartes non choisies par les joueurs
Definition at line 28 of file creation.c.
{
     int choixCarte;
     for(int i=0; i<4; i++){
         // On teste des cartes jusqu'à en trouver 4 qui ne soient pas déjà choisies
         do{
             choixCarte = (rand() % 104);
         }while(Jeu->pioche[choixCarte].carteDraft);
         Jeu->series[0][i]=Jeu->pioche[choixCarte];
     }
     Carte NeutreCarte;
     NeutreCarte.teteDeboeuf = 0;
     NeutreCarte.valeur = 0;
     // On initialise des cartes neutres dans toutes les autres cartes du tableau des séries
     for(int l = 1; l < 5 ; l++){
         for(int c =0; c < 4; c++){
             Jeu->series[l][c] = NeutreCarte;
         }
     }
 }
References Carte::carteDraft, Jeux::pioche, Jeux::series, Carte::teteDeboeuf, and Carte::valeur.
Referenced by tour2Jeu().
creationTabJoueur()
creationTabJoueur (Jeux * Jeu, int nbHumains, int nbJoueurs, int nbBots)
Création d'un tableau de joueurs avec leurs infos respectives.
Author
Etienne Massonnet
Date
May 29th, 2023 5:33 PM
Precondition
Prend en paramètre le pointeur Jeu et le nombre d'humains/bots/joueurs
Postcondition
Le tableau de joueurs est mis à jour
Definition at line 6 of file creation.c.
{
     Jeu->nbJoueurs = nbJoueurs;
     Jeu->tabJoueurs = malloc(Jeu->nbJoueurs * sizeof(Joueur));
     // Demande des noms des joueurs + ajout dans le tableau de joueurs
     for(int idHumain = 0; idHumain < nbHumains;idHumain++){
         char* nomHumain;
         nomHumain = malloc(TAILLEMAX * sizeof(char));
         printf("\nVeuillez saisir un prénom pour le joueur n°%d : ", idHumain+1);
         scanf("%s",nomHumain);
         creationJoueur(Jeu,idHumain,1,nomHumain);
     }
     // Création des noms des bots + ajout dans le tableau de joueurs
     for(int idBot = nbHumains; idBot < nbJoueurs;idBot++){
         char* nomBot = malloc(TAILLEMAX * sizeof(char));
         char buffer[10];
         sprintf(buffer,"Bot%d",idBot+1);
         nomBot = strdup(buffer);
         creationJoueur(Jeu,idBot,0,nomBot);
     }
 }
References creationJoueur(), Jeux::nbJoueurs, Jeux::tabJoueurs, and TAILLEMAX.
Referenced by affMenu0Arg(), affMenu2Arg(), and affMenu3Arg().
initialiserOrdrePassage()
initialiserOrdrePassage (Jeux * Jeu)
Permet d'initialiser un tableau de joueur OrdrePassage.
Authors
Paul Brechenmacher & Nathan Goncalves
Date
31 mai
Precondition
Prend le pointeur Jeu, pour allouer un tableau dynamique de taille nbJoueur
Postcondition
tableau OrdreDePassage initialisé
Definition at line 179 of file creation.c.
{
     for(int idJoueur = 0; idJoueur < Jeu->nbJoueurs; idJoueur++){
         Jeu->tabJoueurs[idJoueur].nb_cartes = 10;
     }
     Jeu->ordreDePassage = malloc(Jeu->nbJoueurs * sizeof(Joueur));
 }
References Joueur::nb_cartes, Jeux::nbJoueurs, Jeux::ordreDePassage, and Jeux::tabJoueurs.
Referenced by mancheJoueurs().