ProjetP1: etienne.c File Reference
etienne.c File Reference
#include "etienne.h"
#include "nathan.h"
#include "structure.h"
#include <stdlib.h>
Functions
void emptyBuffer ()
: vide le buffer après une saisie
void demandeNivBots (Jeux *Jeu)
: demande à l'utilisateur le niveau des bots
void demandeVariante (Jeux *Jeu)
: demande à l'utilisateur le mode de jeu souhaité
void lancementArg (Jeux *Jeu, int argc, char *argv[])
: demande à l'utilisateur le niveau des bots
void affMenu0Arg (Jeux *Jeu)
: demande à l'utilisateur le niveau des bots
void affMenu2Arg (Jeux *Jeu, int argc, char *argv[])
: demande à l'utilisateur le niveau des bots
void affMenu3Arg (Jeux *Jeu, int argc, char *argv[])
: demande à l'utilisateur le niveau des bots
void creationTabJoueur (Jeux *Jeu, int nbHumains, int nbJoueurs, int nbBots)
: demande à l'utilisateur le niveau des bots
void afficherCarte (Carte carte, int etat)
: demande à l'utilisateur le niveau des bots
void affichageLogo ()
: demande à l'utilisateur le niveau des bots
Function Documentation
affichageLogo()
void affichageLogo ()
: demande à l'utilisateur le niveau des bots
Author
: Etienne Massonnet
Date
: 14 juin 2023
Precondition
:
Postcondition
:
Definition at line 286 of file etienne.c.
                     {
     system("clear");
     printf(BYEL);
     printf("/$$                        /$$$$$$                            /$$                                                     /$$ \n");
     printf("| $$                       /$$__  $$                          |__/                                                    | $$\n");
     printf("| $$        /$$$$$$       | $$  |__/        /$$$$$$  /$$   /$$ /$$        /$$$$$$   /$$$$$$   /$$$$$$  /$$$$$$$   /$$$$$$$\n");
     printf("| $$       /$$__  $$      | $$$$$$$        /$$__  $$| $$  | $$| $$       /$$__  $$ /$$__  $$ /$$__  $$| $$__  $$ /$$__  $$\n");
     printf("| $$      | $$$$$$$$      | $$__  $$      | $$  | $$| $$  | $$| $$      | $$  | $$| $$  |__/| $$$$$$$$| $$  | $$| $$  | $$\n");
     printf("| $$      | $$_____/      | $$  | $$      | $$  | $$| $$  | $$| $$      | $$  | $$| $$      | $$_____/| $$  | $$| $$  | $$\n");
     printf("| $$$$$$$$|  $$$$$$$      |  $$$$$$/      |  $$$$$$$|  $$$$$$/| $$      | $$$$$$$/| $$      |  $$$$$$$| $$  | $$|  $$$$$$$\n");
     printf("|________/ |_______/       |______/        |____  $$ |______/ |__/      | $$____/ |__/       |_______/|__/  |__/ |_______/\n");
     printf("                                                | $$                    | $$                                              \n");
     printf("                                                | $$                    | $$                                              \n");
     printf("                                                |__/                    |__/                                              \n");
     printf(reset);
 }
References BYEL, and reset.
Referenced by startJeu().
afficherCarte()
void afficherCarte (Carte carte, int etat)
: demande à l'utilisateur le niveau des bots
Author
: Etienne Massonnet
Date
: 14 juin 2023
Precondition
:
Postcondition
:
Definition at line 218 of file etienne.c.
{
     if(etat == CARTE_MAIN_JOUE){
         printf(BBLK"\e[1;90m""[%s / %d🐮]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
         printf(reset);
     }else{
         switch(carte.teteDeboeuf){
         case BLANC_VIOLET:
             // printf(BPUR"┌━━━━━━┐"reset"\n");
             // printf(BPUR"|"WHTHB BBLK"%s "reset BPUR"|"reset"\n",intCarteToCharCarte(carte.valeur));
             // printf(BPUR"|"WHTHB"🐮  🐮"reset BPUR"|"reset"\n");
             // printf(BPUR"|"WHTHB BBLK"  0%d  "reset BPUR"|"reset"\n",carte.teteDeboeuf);
             // printf(BPUR"┗━━━━━━┛"reset"\n");
             printf(BPUR"["WHTHB BBLK"%s "BPUR"/ "BBLK"%d🐮"reset BPUR"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
          case BLEU_CYAN:
             // printf(BBLU"┌━━━━━━┐"reset"\n");
             // printf(BBLU"|"CYAHB BBLK"%s "reset BBLU"|"reset"\n",intCarteToCharCarte(carte.valeur));
             // printf(BBLU"|"CYAHB"🐮  🐮"reset BBLU"|"reset"\n");
             // printf(BBLU"|"CYAHB BBLK"  0%d  "reset BBLU"|"reset"\n",carte.teteDeboeuf);
             // printf(BBLU"┗━━━━━━┛"reset"\n");
             printf(BBLU"["CYAHB BBLK"%s "BBLU"/ "BBLK"%d🐮"reset BBLU"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
          case VERT_JAUNE:
             // printf(BGRN"┌━━━━━━┐"reset"\n");
             // printf(BGRN"|"GRNHB BORA"%s"reset BGRN"|"reset"\n",intCarteToCharCarte(carte.valeur));
             // printf(BGRN"|"GRNHB"🐮  🐮"reset BGRN"|"reset"\n");
             // printf(BGRN"|"GRNHB BORA"  0%d  "reset BGRN"|"reset"\n",carte.teteDeboeuf);
             // printf(BGRN"┗━━━━━━┛"reset"\n");
             printf(BGRN"["GRNHB BORA"%s "BBLK"/ "BORA"%d🐮"reset BGRN"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
          case ROUGE_VERT:
             // printf(BBLU"┌━━━━━━┐"reset"\n");
             // printf(BBLU"|"REDHB BGRN"%s "reset BBLU"|"reset"\n",intCarteToCharCarte(carte.valeur));
             // printf(BBLU"|"REDHB"🐮  🐮"reset BBLU"|"reset"\n");
             // printf(BBLU"|"REDHB BGRN"  0%d  "reset BBLU"|"reset"\n",carte.teteDeboeuf);
             // printf(BBLU"┗━━━━━━┛"reset"\n");
             printf(BBLU"["REDHB BGRN"%s "BBLU"/ "BGRN"%d🐮"reset BBLU"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
          case VIOLET_ORANGE:
             // printf(BRED"┌━━━━━━┐"reset"\n");
             // printf(BRED"|"PURHB BORA"%s "reset BRED"|"reset"\n",intCarteToCharCarte(carte.valeur));
             // printf(BRED"|"PURHB"🐮  🐮"reset BRED"|"reset"\n");
             // printf(BRED"|"PURHB BORA"  0%d  "reset BRED"|"reset"\n",carte.teteDeboeuf);
             // printf(BRED"┗━━━━━━┛"reset"\n");
             printf(BRED"["PURHB BORA"%s "BRED"/ "BORA"%d🐮"reset BRED"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
         default:
             printf("[%s / %d] ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
         }
     }
 }
References BBLK, BBLU, BGRN, BLANC_VIOLET, BLEU_CYAN, BORA, BPUR, BRED, CARTE_MAIN_JOUE, CYAHB, GRNHB, intCarteToCharCarte(), PURHB, REDHB, reset, ROUGE_VERT, Carte::teteDeboeuf, Carte::valeur, VERT_JAUNE, VIOLET_ORANGE, and WHTHB.
Referenced by afficherMainJoueur(), afficherSeries(), and choixColonneJoueeHumain().
affMenu0Arg()
void affMenu0Arg (Jeux * Jeu)
: demande à l'utilisateur le niveau des bots
Author
: Etienne Massonnet
Date
: 14 juin 2023
Precondition
:
Postcondition
:
Definition at line 106 of file etienne.c.
{
     int nbJoueurs,nbHumains,nbBots;
     printf(BWHT"\n┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ Bienvenue ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n\n");
     printf("\nEntrez le nombre souhaité de joueurs au total ("BGRN"humains "BWHT"ou "BRED"bots"BWHT") entre 2 et 10 inclus : ");
     scanf("%d", &nbJoueurs);
     while (nbJoueurs>10 || nbJoueurs<2){
         emptyBuffer();
         printf(BRED"\n /!\\ Erreur de saisie : entrez un nombre entier entre 2 et 10 inclus : "BWHT);
         scanf("%d", &nbJoueurs);
     }
     printf("Parmi ces %d joueurs, combien y a-t-il d'humains ? : ", nbJoueurs);
     scanf("%d", &nbHumains);
     while (nbHumains<0 || nbHumains>nbJoueurs){
         emptyBuffer();
         printf(BRED"\n /!\\ Erreur de saisie : entrez un nombre entier entre 0 et %d inclus : "reset, nbJoueurs);
         scanf("%d", &nbHumains);
     }
     nbBots=nbJoueurs-nbHumains;
     creationTabJoueur(Jeu,nbHumains,nbJoueurs,nbBots);
     demandeVariante(Jeu);
     if (nbBots>0){
         demandeNivBots(Jeu);
     }
 }
References BGRN, BRED, BWHT, creationTabJoueur(), demandeNivBots(), demandeVariante(), emptyBuffer(), and reset.
Referenced by lancementArg().
affMenu2Arg()
void affMenu2Arg (Jeux * Jeu, int argc, char * argv[])
: demande à l'utilisateur le niveau des bots
Author
: Etienne Massonnet
Date
: 14 juin 2023
Precondition
:
Postcondition
:
Definition at line 142 of file etienne.c.
{
     printf(BWHT"\n┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ Bienvenue ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n\n");
     int nbBots=atoi(argv[1]);
     int nbHumains=atoi(argv[2]);
     int nbJoueurs=nbBots+nbHumains;
     printf("\nVous avez choisi de jouer avec %d bots et %d humains\n"reset,nbBots,nbHumains);
     creationTabJoueur(Jeu,nbHumains,nbJoueurs,nbBots);
     demandeVariante(Jeu);
     if (nbBots>0){
         demandeNivBots(Jeu);
     }
 }
References BWHT, creationTabJoueur(), demandeNivBots(), demandeVariante(), and reset.
Referenced by lancementArg().
affMenu3Arg()
void affMenu3Arg (Jeux * Jeu, int argc, char * argv[])
: demande à l'utilisateur le niveau des bots
Author
: Etienne Massonnet
Date
: 14 juin 2023
Precondition
:
Postcondition
:
Definition at line 164 of file etienne.c.
{
     printf(BWHT"\n┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ Bienvenue ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n\n");
     int nbBots=atoi(argv[1]);
     int nbHumains=atoi(argv[2]);
     int nbJoueurs=nbBots+nbHumains;
     Jeu->seuil = atoi(argv[3]);
     printf("\nVous avez choisi de jouer avec %d bots et %d humains, avec un seuil de %d têtes de boeuf.\n"reset,nbBots,nbHumains,Jeu->seuil );
     creationTabJoueur(Jeu,nbHumains,nbJoueurs,nbBots);
     demandeVariante(Jeu);
     if (nbBots>0){
         demandeNivBots(Jeu);
     }
 }
References BWHT, creationTabJoueur(), demandeNivBots(), demandeVariante(), reset, and Jeux::seuil.
Referenced by lancementArg().
creationTabJoueur()
void creationTabJoueur (Jeux * Jeu, int nbHumains, int nbJoueurs, int nbBots)
: demande à l'utilisateur le niveau des bots
Author
: Etienne Massonnet
Date
: 14 juin 2023
Precondition
:
Postcondition
:
Definition at line 189 of file etienne.c.
{
     Jeu->nbJoueurs = nbJoueurs;
     Jeu->tabJoueurs = malloc(Jeu->nbJoueurs * sizeof(Joueur));
     for(int idHumain = 0; idHumain < nbHumains;idHumain++){
         char* nomHumain;
         nomHumain = malloc(TAILLEMAX * sizeof(char));
         printf("\nVeuillez saisir un prénom pour le joueur n°%d : ", idHumain+1);
         scanf("%s",nomHumain);
         creationJoueur(Jeu,idHumain,1,nomHumain);
     }
     for(int idBot = nbHumains; idBot < nbJoueurs;idBot++){
         char* nomBot = malloc(TAILLEMAX * sizeof(char));
         char buffer[10];
         sprintf(buffer,"Bot%d",idBot+1);
         nomBot = strdup(buffer);
         creationJoueur(Jeu,idBot,0,nomBot);
     }
 }
References creationJoueur(), Jeux::nbJoueurs, Jeux::tabJoueurs, and TAILLEMAX.
Referenced by affMenu0Arg(), affMenu2Arg(), and affMenu3Arg().
demandeNivBots()
void demandeNivBots (Jeux * Jeu)
: demande à l'utilisateur le niveau des bots
Author
: Etienne Massonnet
Date
: 14 juin 2023
Precondition
:
Postcondition
:
Definition at line 24 of file etienne.c.
{
     int niveau;
     printf(BWHT"\nDifficulté des bots :\n"reset);
     printf(BGRN"> Niveau 1 : Facile\n"BORA"> Niveau 2 : Moyen\n"BRED"> Niveau 3 : Difficile\n\n"BWHT"Choisissez un niveau (1/2/3): "reset);
     scanf("%d", &niveau);
     while(niveau<1 || niveau >3){
         emptyBuffer();
         printf(BRED"\n /!\\ Erreur de saisie : entrez un nombre entier entre 1 et 3 inclus : "reset);
         scanf("%d", &niveau);
     }
     Jeu->niveauBots=niveau-1;
 }
References BGRN, BORA, BRED, BWHT, emptyBuffer(), Jeux::niveauBots, and reset.
Referenced by affMenu0Arg(), affMenu2Arg(), and affMenu3Arg().
demandeVariante()
void demandeVariante (Jeux * Jeu)
: demande à l'utilisateur le mode de jeu souhaité
Author
: Etienne Massonnet
Date
: 14 juin 2023
Precondition
:
Postcondition
:
Definition at line 44 of file etienne.c.
{
     int choix;
     printf(BWHT"\nModes de jeu :\n"reset);
     printf(BWHT"> Mode 1 : Jeu classique\n"BGRN"> Mode 2 : Variante \"Avec nombre défini\"\n"BYEL"> Mode 3 : Variante \"Draft\"\n\n"BWHT"Choisissez un mode de jeu (1/2/3): "reset);
     scanf("%d", &choix);
     while(choix<1 || choix>3){
         emptyBuffer();
         printf(BRED"\n /!\\ Erreur de saisie : entrez un nombre entier entre 1 et 3 inclus : "reset);
         scanf("%d", &choix);
     }
     Jeu->variante=choix-1;
 }
References BGRN, BRED, BWHT, BYEL, emptyBuffer(), reset, and Jeux::variante.
Referenced by affMenu0Arg(), affMenu2Arg(), and affMenu3Arg().
emptyBuffer()
void emptyBuffer ()
: vide le buffer après une saisie
Author
: Peio Loubière peio..nosp@m.loub.nosp@m.iere@.nosp@m.cyu..nosp@m.fr
Date
: Thu Nov 19 17:07:41 2020
Definition at line 12 of file etienne.c.
                    {
   char c;
   while (((c = getchar()) != '\n') && (c != EOF));
 }
Referenced by affMenu0Arg(), choixColonneJoueeHumain(), creationCarteJoue(), demandeNivBots(), and demandeVariante().
lancementArg()
void lancementArg (Jeux * Jeu, int argc, char * argv[])
: demande à l'utilisateur le niveau des bots
Author
: Etienne Massonnet
Date
: 14 juin 2023
Precondition
:
Postcondition
:
Definition at line 67 of file etienne.c.
{
     //vérification des arguments
     Jeu->seuil = 66;
     if(argc>1){
         if(argc==2){
             printf("ERREUR : Si vous souhaitez utiliser des arguments, choisissez deux entiers dont la somme est comprise entre 2 et 10. Un troisième argument (entier naturel) peut être entré pour choisir le seuil de têtes de boeuf entraînant la fin de la partie.\n");
             exit(EXIT_SUCCESS);
         }else{
             int total = atoi(argv[1])+atoi(argv[2]);
             if( (total < 2 || total >10) || argc > 4){
                 printf("ERREUR : Si vous souhaitez utiliser des arguments, choisissez deux entiers dont la somme est comprise entre 2 et 10. Un troisième argument (entier naturel) peut être entré pour choisir le seuil de têtes de boeuf entraînant la fin de la partie.\n");
                 exit(EXIT_SUCCESS);
             }
         }
     }
     switch(argc){
         case 1 : affMenu0Arg(Jeu);
                 break;
         case 3 : affMenu2Arg(Jeu, argc, argv);
                 break;
         case 4 : affMenu3Arg(Jeu, argc, argv);
                 break;
         default : break;
     }
 }
References affMenu0Arg(), affMenu2Arg(), affMenu3Arg(), and Jeux::seuil.
Referenced by startJeu().