ProjetP1: etienne.h File Reference
etienne.h File Reference
#include "structure.h"
Functions
void emptyBuffer ()
: Vide le buffer après une saisie
void demandeNivBots (Jeux *Jeu)
: Demande à l'utilisateur le niveau des bots
void demandeVariante (Jeux *Jeu)
: Demande à l'utilisateur le mode de jeu souhaité
void lancementArg (Jeux *Jeu, int argc, char *argv[])
: Affiche le menu de début de jeu de plusieurs manières en fonction du nombre d'arguments utilisés
void affMenu0Arg (Jeux *Jeu)
: Affiche le menu demande à l'utilisateur le nombre de joueurs et de bots, leurs noms, le mode de jeu , le niveau des bots
void affMenu2Arg (Jeux *Jeu, int argc, char *argv[])
: Affiche le menu et demande à l'utilisateur le mode de jeu souhaité et le niveau des bots
void affMenu3Arg (Jeux *Jeu, int argc, char *argv[])
: affiche le menu et demande à l'utilisateur le mode de jeu souhaité et le niveau des bots
void creationTabJoueur (Jeux *Jeu, int nbHumains, int nbJoueurs, int nbBots)
: Création d'un tableau de joueurs avec leurs infos respectives
void afficherCarte (Carte carte, int etat)
: Affiche une carte de manière différente en fonction de son état
void affichageLogo ()
: affiche "Le 6 qui prend" lorsque le jeu est lancé
void choixCarteBotHard (Jeux *Jeu, int idBot)
: Détermine la carte que choisit le bot de niveau difficile
void creationSeriesDraft (Jeux *Jeu)
: Constitue les séries
void afficherDraft (Jeux Jeu)
: Affiche la totalité des cartes de la pioche
void choixCartesDraft (Jeux *Jeu)
: Fait choisir aux joueurs leurs 10 cartes, une par une, parmi la pioche
void distributionPiocheDraft (Jeux *Jeu)
: Constitue les mains de tous les joueurs et les séries
Function Documentation
affichageLogo()
void affichageLogo ()
: affiche "Le 6 qui prend" lorsque le jeu est lancé
Authors
: Etienne Massonnet, Paul Brechenmacher
Date
: June 13th, 2023 12:04 AM
Definition at line 196 of file etienne.c.
                     {
     system("clear");
     printf(BYEL);
     printf("/$$                        /$$$$$$                            /$$                                                     /$$ \n");
     printf("| $$                       /$$__  $$                          |__/                                                    | $$\n");
     printf("| $$        /$$$$$$       | $$  |__/        /$$$$$$  /$$   /$$ /$$        /$$$$$$   /$$$$$$   /$$$$$$  /$$$$$$$   /$$$$$$$\n");
     printf("| $$       /$$__  $$      | $$$$$$$        /$$__  $$| $$  | $$| $$       /$$__  $$ /$$__  $$ /$$__  $$| $$__  $$ /$$__  $$\n");
     printf("| $$      | $$$$$$$$      | $$__  $$      | $$  | $$| $$  | $$| $$      | $$  | $$| $$  |__/| $$$$$$$$| $$  | $$| $$  | $$\n");
     printf("| $$      | $$_____/      | $$  | $$      | $$  | $$| $$  | $$| $$      | $$  | $$| $$      | $$_____/| $$  | $$| $$  | $$\n");
     printf("| $$$$$$$$|  $$$$$$$      |  $$$$$$/      |  $$$$$$$|  $$$$$$/| $$      | $$$$$$$/| $$      |  $$$$$$$| $$  | $$|  $$$$$$$\n");
     printf("|________/ |_______/       |______/        |____  $$ |______/ |__/      | $$____/ |__/       |_______/|__/  |__/ |_______/\n");
     printf("                                                | $$                    | $$                                              \n");
     printf("                                                | $$                    | $$                                              \n");
     printf("                                                |__/                    |__/                                              \n");
     printf(reset);
 }
References BYEL, and reset.
Referenced by startJeu().
afficherCarte()
void afficherCarte (Carte carte, int etat)
: Affiche une carte de manière différente en fonction de son état
Authors
: Etienne Massonnet, Paul Brechenmacher
Date
: June 12th, 2023 6:30 PM
Precondition
: Prend en paramètre une carte et son état (défini par l'énumération etat)
Postcondition
: La carte est affichée d'une couleur différente en fonction de sa valeur, comme dicté par les règles du jeu
Definition at line 154 of file etienne.c.
{
     if(etat == CARTE_MAIN_JOUE){
         // Si la carte a déjà été jouée, elle est affichée en noir
         printf(BBLK"\e[1;90m""[%s / %d🐮]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
         printf(reset);
     }else{
         /* Sinon, elle est affichée d'une couleur différente en fonction de son nombre de TDB :
         - 1 TDB : Blanche
         - 2 TDB : Bleue
         - 3 TDB : Verte
         - 5 TDB : Rouge
         - 7 TDB : Rose
         */
         switch(carte.teteDeboeuf){
         case BLANC_VIOLET:
             printf(BPUR"["WHTHB BBLK"%s "BPUR"/ "BBLK"%d🐮"reset BPUR"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
          case BLEU_CYAN:
             printf(BBLU"["CYAHB BBLK"%s "BBLU"/ "BBLK"%d🐮"reset BBLU"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
          case VERT_JAUNE:
             printf(BGRN"["GRNHB BORA"%s "BBLK"/ "BORA"%d🐮"reset BGRN"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
          case ROUGE_VERT:
             printf(BBLU"["REDHB BGRN"%s "BBLU"/ "BGRN"%d🐮"reset BBLU"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
          case VIOLET_ORANGE:
             printf(BRED"["PURHB BORA"%s "BRED"/ "BORA"%d🐮"reset BRED"]"reset" ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
         default:
             printf("[%s / %d] ",intCarteToCharCarte(carte.valeur),carte.teteDeboeuf);
             break;
         }
     }
 }
References BBLK, BBLU, BGRN, BLANC_VIOLET, BLEU_CYAN, BORA, BPUR, BRED, CARTE_MAIN_JOUE, CYAHB, GRNHB, intCarteToCharCarte(), PURHB, REDHB, reset, ROUGE_VERT, Carte::teteDeboeuf, Carte::valeur, VERT_JAUNE, VIOLET_ORANGE, and WHTHB.
Referenced by afficherDraft(), afficherMainJoueur(), afficherSeries(), and choixColonneJoueeHumain().
afficherDraft()
void afficherDraft (Jeux Jeu)
: Affiche la totalité des cartes de la pioche
Authors
: Etienne Massonnet, Nathan Goncalves
Date
: June 18th, 2023 23:35 PM
Precondition
: Prend en argument le jeu
Postcondition
: Affiche dans le terminal toutes les cartes de la pioche, par lignes de 10 et dans l'ordre croissant
Definition at line 259 of file etienne.c.
{
     printf("\n");
     // On affiche les 100 premières cartes par lignes de 10
     for(int j=0; j<10; j++){
         for (int i=j*10; i<j*10+10; i++){
             if (Jeu.pioche[i].carteDraft){
                 afficherCarte(Jeu.pioche[i], 1);
             }else{
                 afficherCarte(Jeu.pioche[i], 0);
             }
         }
         printf("\n\n");
     }
     // On affiche les 4 dernières cartes
     for(int k=100; k<104; k++){
         if (Jeu.pioche[k].carteDraft){
             afficherCarte(Jeu.pioche[k], 1);
         }else{
             afficherCarte(Jeu.pioche[k], 0);
         }
     }
     printf("\n\n");
 }
References afficherCarte(), Carte::carteDraft, and Jeux::pioche.
Referenced by choixCartesDraft(), and distributionPiocheDraft().
affMenu0Arg()
void affMenu0Arg (Jeux * Jeu)
: Affiche le menu demande à l'utilisateur le nombre de joueurs et de bots, leurs noms, le mode de jeu , le niveau des bots
Author
: Etienne Massonnet
Date
: May 29th, 2023 5:33 PM
Precondition
: Prend en paramètre le jeu complet
Postcondition
: Affiche le menu et stocke dans des variables les réponses de l'utilisateur, initialise le tableau de joueurs grâce à creationTabJoueur
Definition at line 73 of file etienne.c.
{
     int nbJoueurs,nbHumains,nbBots;
     printf(BWHT"\n┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ Bienvenue ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n\n");
     printf("\nEntrez le nombre souhaité de joueurs au total ("BGRN"humains "BWHT"ou "BRED"bots"BWHT") entre 2 et 10 inclus : ");
     scanf("%d", &nbJoueurs);
     // Sécurité en cas de saisie invalide
     while (nbJoueurs>10 || nbJoueurs<2){
         emptyBuffer();
         printf(BRED"\n /!\\ Erreur de saisie : entrez un nombre entier entre 2 et 10 inclus : "BWHT);
         scanf("%d", &nbJoueurs);
     }
     printf("Parmi ces %d joueurs, combien y a-t-il d'humains ? : ", nbJoueurs);
     scanf("%d", &nbHumains);
     // Sécurité en cas de saisie invalide
     while (nbHumains<0 || nbHumains>nbJoueurs){
         emptyBuffer();
         printf(BRED"\n /!\\ Erreur de saisie : entrez un nombre entier entre 0 et %d inclus : "reset, nbJoueurs);
         scanf("%d", &nbHumains);
     }
     nbBots=nbJoueurs-nbHumains;
     creationTabJoueur(Jeu,nbHumains,nbJoueurs,nbBots);
     demandeVariante(Jeu);
     if (nbBots>0){
         demandeNivBots(Jeu);
     }
 }
References BGRN, BRED, BWHT, creationTabJoueur(), demandeNivBots(), demandeVariante(), emptyBuffer(), and reset.
Referenced by lancementArg().
affMenu2Arg()
void affMenu2Arg (Jeux * Jeu, int argc, char * argv[])
: Affiche le menu et demande à l'utilisateur le mode de jeu souhaité et le niveau des bots
Author
: Etienne Massonnet
Date
: May 29th, 2023 5:33 PM
Precondition
: Prend en paramètre le pointeur Jeu, ainsi que les arguments
Postcondition
: Affiche le menu et stocke dans des variables les réponses de l'utilisateur, initialise le tableau de joueurs grâce à creationTabJoueur
Definition at line 102 of file etienne.c.
{
     printf(BWHT"\n┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ Bienvenue ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n\n");
     int nbBots=atoi(argv[1]);
     int nbHumains=atoi(argv[2]);
     int nbJoueurs=nbBots+nbHumains;
     printf("\nVous avez choisi de jouer avec %d bots et %d humains\n"reset,nbBots,nbHumains);
     creationTabJoueur(Jeu,nbHumains,nbJoueurs,nbBots);
     demandeVariante(Jeu);
     if (nbBots>0){
         demandeNivBots(Jeu);
     }
 }
References BWHT, creationTabJoueur(), demandeNivBots(), demandeVariante(), and reset.
Referenced by lancementArg().
affMenu3Arg()
void affMenu3Arg (Jeux * Jeu, int argc, char * argv[])
: affiche le menu et demande à l'utilisateur le mode de jeu souhaité et le niveau des bots
Author
: Etienne Massonnet
Date
: May 29th, 2023 5:33 PM
Precondition
: Prend en paramètre le pointeur Jeu, ainsi que les arguments
Postcondition
: Affiche le menu et stocke dans des variables les réponses de l'utilisateur, initialise le tableau de joueurs grâce à creationTabJoueur
Definition at line 117 of file etienne.c.
{
     printf(BWHT"\n┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ Bienvenue ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n\n");
     int nbBots=atoi(argv[1]);
     int nbHumains=atoi(argv[2]);
     int nbJoueurs=nbBots+nbHumains;
     Jeu->seuil = atoi(argv[3]);
     printf("\nVous avez choisi de jouer avec %d bots et %d humains, avec un seuil de %d têtes de boeuf.\n"reset,nbBots,nbHumains,Jeu->seuil );
     creationTabJoueur(Jeu,nbHumains,nbJoueurs,nbBots);
     demandeVariante(Jeu);
     if (nbBots>0){
         demandeNivBots(Jeu);
     }
 }
References BWHT, creationTabJoueur(), demandeNivBots(), demandeVariante(), reset, and Jeux::seuil.
Referenced by lancementArg().
choixCarteBotHard()
void choixCarteBotHard (Jeux * Jeu, int idBot)
: Détermine la carte que choisit le bot de niveau difficile
Authors
: Etienne Massonnet, Nathan Goncalves
Date
: June 17th, 2023 12:15 AM
Precondition
: Prend en argument le pointeur Jeu et l'id du bot concerné
Postcondition
: La carte choisie par le bot est celle qui a le plus petit écart avec l'une des séries
Definition at line 213 of file etienne.c.
{
     // Détermine la carte ayant le plus petit écart avec la 1ère carte d'une des séries
     int ecartValeur,choixCarte;
     int minEcartValeur = 105;
     for(int idCarteMain = 0; idCarteMain < 10; idCarteMain++){
         // On vérifie que la carte n'a pas été jouée
         if(!Jeu->tabJoueurs[idBot].mainJoueur[idCarteMain].carteJouee){
             for(int idCarteSeries = 0; idCarteSeries < 4; idCarteSeries++){
                 // Calcule l'écart entre chaque carte de la main du bot et chaque 1ère carte des séries
                 ecartValeur = Jeu->tabJoueurs[idBot].mainJoueur[idCarteMain].valeur - Jeu->series[0][idCarteSeries].valeur;
                 if(ecartValeur > 0){
                     if(ecartValeur < minEcartValeur){
                         minEcartValeur = ecartValeur;
                         choixCarte = idCarteMain;
                     }
                 }
             }
         }
     }
     // On met à jour la carte jouée et on met à jour son statut pour éviter qu'elle soit jouée une 2ème fois
     Jeu->tabJoueurs[idBot].carteJouee = Jeu->tabJoueurs[idBot].mainJoueur[choixCarte];
     Jeu->tabJoueurs[idBot].carteJouee.carteJouee = 1;
 }
choixCartesDraft()
void choixCartesDraft (Jeux * Jeu)
: Fait choisir aux joueurs leurs 10 cartes, une par une, parmi la pioche
Authors
: Etienne Massonnet, Nathan Goncalves
Date
: June 18th, 2023 23:35 PM
Precondition
: Prend en argument le pointeur Jeu
Postcondition
: Constitue les mains des joueurs selon leurs choix, prend des cartes au hasard pour les bots
Definition at line 283 of file etienne.c.
{
     int choixCarte;
     for(int i=0; i<10; i++){
         for(int idjoueur=0; idjoueur<Jeu->nbJoueurs; idjoueur++){
             if(Jeu->tabJoueurs[idjoueur].type){
                 system("clear");
                 // Sécurité en cas de saisie invalide
                 do{
                     afficherDraft(*Jeu);
                     printf(BWHT"\e[4;37m" "Choix de %s :"reset,Jeu->tabJoueurs[idjoueur].nomJoueur);
                     printf(BWHT"\nChoisissez une carte entre 1 et 104 : "reset);
                     scanf("%d", &choixCarte);
                     emptyBuffer();
                     system("clear");
                 }while(choixCarte<0 || choixCarte>104 || Jeu->pioche[choixCarte-1].carteDraft);
             }else{
                 // On teste des cartes à prendre pour le bot jusqu'à en trouver une qui ne soit pas encore choisie
                 do{
                     choixCarte = (rand() % 104)+1;
                 }while(Jeu->pioche[choixCarte-1].carteDraft);
             }
             // La carte choisie est ajoutée à la main du joueur et son statut est modifié pour éviter de la choisir à nouveau
             Jeu->tabJoueurs[idjoueur].mainJoueur[i]=Jeu->pioche[choixCarte-1];
             Jeu->pioche[choixCarte-1].carteDraft=1;
         }
     }
 }
References afficherDraft(), BWHT, Carte::carteDraft, emptyBuffer(), Joueur::mainJoueur, Jeux::nbJoueurs, Joueur::nomJoueur, Jeux::pioche, reset, Jeux::tabJoueurs, and Joueur::type.
Referenced by distributionPiocheDraft().
creationSeriesDraft()
void creationSeriesDraft (Jeux * Jeu)
: Constitue les séries
Authors
: Etienne Massonnet, Nathan Goncalves
Date
: June 18th, 2023 23:35 PM
Precondition
: Prend en argument le pointeur Jeu
Postcondition
: Constitue les séries au hasard, à partir des cartes non choisies par les joueurs
Definition at line 238 of file etienne.c.
{
     int choixCarte;
     for(int i=0; i<4; i++){
         // On teste des cartes jusqu'à en trouver 4 qui ne soient pas déjà choisies
         do{
             choixCarte = (rand() % 104);
         }while(Jeu->pioche[choixCarte].carteDraft);
         Jeu->series[0][i]=Jeu->pioche[choixCarte];
     }
     Carte NeutreCarte;
     NeutreCarte.teteDeboeuf = 0;
     NeutreCarte.valeur = 0;
     // On initialise des cartes neutres dans toutes les autres cartes du tableau des séries
     for(int l = 1; l < 5 ; l++){
         for(int c =0; c < 4; c++){
             Jeu->series[l][c] = NeutreCarte;
         }
     }
 }
References Carte::carteDraft, Jeux::pioche, Jeux::series, Carte::teteDeboeuf, and Carte::valeur.
Referenced by tour2Jeu().
creationTabJoueur()
void creationTabJoueur (Jeux * Jeu, int nbHumains, int nbJoueurs, int nbBots)
: Création d'un tableau de joueurs avec leurs infos respectives
Author
: Etienne Massonnet
Date
: May 29th, 2023 5:33 PM
Precondition
: Prend en paramètre le pointeur Jeu et le nombre d'humains/bots/joueurs
Postcondition
: Le tableau de joueurs est mis à jour
Definition at line 133 of file etienne.c.
{
     Jeu->nbJoueurs = nbJoueurs;
     Jeu->tabJoueurs = malloc(Jeu->nbJoueurs * sizeof(Joueur));
     // Demande des noms des joueurs + ajout dans le tableau de joueurs
     for(int idHumain = 0; idHumain < nbHumains;idHumain++){
         char* nomHumain;
         nomHumain = malloc(TAILLEMAX * sizeof(char));
         printf("\nVeuillez saisir un prénom pour le joueur n°%d : ", idHumain+1);
         scanf("%s",nomHumain);
         creationJoueur(Jeu,idHumain,1,nomHumain);
     }
     // Création des noms des bots + ajout dans le tableau de joueurs
     for(int idBot = nbHumains; idBot < nbJoueurs;idBot++){
         char* nomBot = malloc(TAILLEMAX * sizeof(char));
         char buffer[10];
         sprintf(buffer,"Bot%d",idBot+1);
         nomBot = strdup(buffer);
         creationJoueur(Jeu,idBot,0,nomBot);
     }
 }
References creationJoueur(), Jeux::nbJoueurs, Jeux::tabJoueurs, and TAILLEMAX.
Referenced by affMenu0Arg(), affMenu2Arg(), and affMenu3Arg().
demandeNivBots()
void demandeNivBots (Jeux * Jeu)
: Demande à l'utilisateur le niveau des bots
Author
: Etienne Massonnet
Date
: June 13th, 2023 4:23 PM
Precondition
: Prend le pointeur Jeu pour modifier la valeur Jeu->niveauBots
Postcondition
: La valeur Jeu->niveauBots est mise à jour
Definition at line 14 of file etienne.c.
{
     int niveau;
     printf(BWHT"\nDifficulté des bots :\n"reset);
     printf(BGRN"> Niveau 1 : Facile\n"BORA"> Niveau 2 : Moyen\n"BRED"> Niveau 3 : Difficile\n\n"BWHT"Choisissez un niveau (1/2/3): "reset);
     scanf("%d", &niveau);
     // Sécurité en cas de saisie invalide
     while(niveau<1 || niveau >3){
         emptyBuffer();
         printf(BRED"\n /!\\ Erreur de saisie : entrez un nombre entier entre 1 et 3 inclus : "reset);
         scanf("%d", &niveau);
     }
     Jeu->niveauBots=niveau-1;
 }
References BGRN, BORA, BRED, BWHT, emptyBuffer(), Jeux::niveauBots, and reset.
Referenced by affMenu0Arg(), affMenu2Arg(), and affMenu3Arg().
demandeVariante()
void demandeVariante (Jeux * Jeu)
: Demande à l'utilisateur le mode de jeu souhaité
Author
: Etienne Massonnet
Date
: June 15th, 2023 3:19 AM
Precondition
: Prend le pointeur Jeu pour modifier la valeur Jeu->variante
Postcondition
: La valeur Jeu->variante est mise à jour
Definition at line 28 of file etienne.c.
{
     int choix;
     printf(BWHT"\nModes de jeu :\n"reset);
     printf(BWHT"> Mode 1 : Jeu classique\n"BGRN"> Mode 2 : Variante \"Avec nombre défini\"\n"BYEL"> Mode 3 : Variante \"Draft\"\n\n"BWHT"Choisissez un mode de jeu (1/2/3): "reset);
     scanf("%d", &choix);
     // Sécurité en cas de saisie invalide
     while(choix<1 || choix>3){
         emptyBuffer();
         printf(BRED"\n /!\\ Erreur de saisie : entrez un nombre entier entre 1 et 3 inclus : "reset);
         scanf("%d", &choix);
     }
     Jeu->variante=choix-1;
 }
References BGRN, BRED, BWHT, BYEL, emptyBuffer(), reset, and Jeux::variante.
Referenced by affMenu0Arg(), affMenu2Arg(), and affMenu3Arg().
distributionPiocheDraft()
void distributionPiocheDraft (Jeux * Jeu)
: Constitue les mains de tous les joueurs et les séries
Authors
: Etienne Massonnet, Nathan Goncalves
Date
: June 18th, 2023 23:35 PM
Precondition
: Prend en argument le pointeur Jeu
Postcondition
: Les mains des joueurs sont pleines, les séries sont en place
Definition at line 312 of file etienne.c.
{
     // Le statut des cartes est réinitialisé pour qu'on puisse les choisir à nouveau
     for(int i=0; i<104;i++){
         Jeu->pioche[i].carteDraft = 0;
     }
     afficherDraft(*Jeu);
     choixCartesDraft(Jeu);
 }
References afficherDraft(), Carte::carteDraft, choixCartesDraft(), and Jeux::pioche.
Referenced by tour2Jeu().
emptyBuffer()
void emptyBuffer ()
: Vide le buffer après une saisie
Author
: Peio Loubière peio..nosp@m.loub.nosp@m.iere@.nosp@m.cyu..nosp@m.fr
Date
: Thu Nov 19 17:07:41 2020
Definition at line 9 of file etienne.c.
                    {
   char c;
   while (((c = getchar()) != '\n') && (c != EOF));
 }
Referenced by affMenu0Arg(), choixCartesDraft(), choixColonneJoueeHumain(), creationCarteJoue(), demandeNivBots(), and demandeVariante().
lancementArg()
void lancementArg (Jeux * Jeu, int argc, char * argv[])
: Affiche le menu de début de jeu de plusieurs manières en fonction du nombre d'arguments utilisés
Author
: Etienne Massonnet
Date
: June 12th, 2023 2:27 PM
Precondition
: Prend le pointeur Jeu, le nombre d'arguments entrés et les arguments en question
Postcondition
: Le menu est affiché de manière adaptée aux arguments
Definition at line 42 of file etienne.c.
{
     // Vérification des arguments entrés
     Jeu->seuil = 66;
     if(argc>1){
         if(argc==2){
             printf("ERREUR : Si vous souhaitez utiliser des arguments, choisissez deux entiers dont la somme est comprise entre 2 et 10. Un troisième argument (entier naturel) peut être entré pour choisir le seuil de têtes de boeuf entraînant la fin de la partie.\n");
             exit(EXIT_SUCCESS);
         }else{
             int total = atoi(argv[1])+atoi(argv[2]);
             if( (total < 2 || total >10) || argc > 4){
                 printf("ERREUR : Si vous souhaitez utiliser des arguments, choisissez deux entiers dont la somme est comprise entre 2 et 10. Un troisième argument (entier naturel) peut être entré pour choisir le seuil de têtes de boeuf entraînant la fin de la partie.\n");
                 exit(EXIT_SUCCESS);
             }
         }
     }
     // Lancement de menu différent selon les arguments
     switch(argc){
         case 1 :
                 affMenu0Arg(Jeu);
                 break;
         case 3 :
                 affMenu2Arg(Jeu, argc, argv);
                 break;
         case 4 :
                 affMenu3Arg(Jeu, argc, argv);
                 break;
         default :
                 break;
     }
 }
References affMenu0Arg(), affMenu2Arg(), affMenu3Arg(), and Jeux::seuil.
Referenced by startJeu().