ProjetP1: nathan.h File Reference
nathan.h File Reference
#include "structure.h"
Functions
void initialiserJoueur (Joueur *j, char *Prenom)
void creationJoueur (Jeux *Jeu, int id, int type, char *nomJoueur)
void creationSeries (Jeux *Jeu)
void afficherSeries (Jeux Jeu)
void afficherJeu (Jeux Jeu)
: Permet d'afficher tout le Jeu
Function Documentation
afficherJeu()
: afficherJeu (Jeux Jeu)
: Permet d'afficher tout le Jeu
Authors
: Paul Brechenmacher & Etienne Massonnet
Date
: --—
Precondition
: Prend la stucture Jeu, pour afficher l'entièreté du jeu
Postcondition
: Affichage du jeu
Definition at line 329 of file paul.c.
{
     afficherSeries(Jeu);
 }
References afficherSeries().
Referenced by choixColonneJoueeHumain(), creationCarteJoue(), mancheJoueurs(), and placementSeries().
afficherSeries()
void afficherSeries (Jeux Jeu)
Definition at line 53 of file nathan.c.
{
     Carte NeutreCarte;
     NeutreCarte.teteDeboeuf = 0;
     NeutreCarte.valeur = 0;
     for(int l = 0; l < 5 ; l++){
         for(int c =0; c < 4; c++){
             if (Jeu.series[l][c].valeur != NeutreCarte.valeur && Jeu.series[l][c].teteDeboeuf != NeutreCarte.teteDeboeuf){
                 afficherCarte(Jeu.series[l][c],CARTE_SERIES);
             }else{
                 printf("            ");
             }
         }
         printf("\n");
     }
 }
References afficherCarte(), CARTE_SERIES, Jeux::series, Carte::teteDeboeuf, and Carte::valeur.
Referenced by afficherJeu().
creationJoueur()
void creationJoueur (Jeux * Jeu, int id, int type, char * nomJoueur)
Definition at line 10 of file nathan.c.
{
     Jeu->tabJoueurs[id].nomJoueur = malloc(TAILLEMAX*sizeof(char));
     Jeu->tabJoueurs[id].mainJoueur = malloc(10*sizeof(Carte));
     Jeu->tabJoueurs[id].id = id;
     Jeu->tabJoueurs[id].type = type;
     Jeu->tabJoueurs[id].nomJoueur = nomJoueur;
 }
References Joueur::id, Joueur::mainJoueur, Joueur::nomJoueur, Jeux::tabJoueurs, TAILLEMAX, and Joueur::type.
Referenced by creationTabJoueur().
creationSeries()
void creationSeries (Jeux * Jeu)
Definition at line 26 of file nathan.c.
{
     int carteUsed;
     Carte NeutreCarte;
     NeutreCarte.teteDeboeuf = 0;
     NeutreCarte.valeur = 0;
     // Initialisation //
     for(int l = 0; l < 5 ; l++){
         for(int c =0; c < 4; c++){
             Jeu->series[l][c] = NeutreCarte;
         }
     }
     //Création premières cartes des séries//
     carteUsed = (Jeu->nbJoueurs) * 10;
     int idCarte = 0;
     for(int idCarteUsed = carteUsed; idCarteUsed < carteUsed + 4;idCarteUsed++){
         Jeu->series[0][idCarte] = Jeu->pioche[idCarteUsed];
         idCarte++;
     }
 }
References Jeux::nbJoueurs, Jeux::pioche, Jeux::series, Carte::teteDeboeuf, and Carte::valeur.
Referenced by tour2Jeu().
initialiserJoueur()
void initialiserJoueur (Joueur * j, char * Prenom)