ProjetP1: paul.c File Reference
paul.c File Reference
#include "paul.h"
#include "etienne.h"
#include "adrien.h"
#include "nathan.h"
#include "structure.h"
#include <stdio.h>
#include <unistd.h>
Functions
void startJeu (Jeux *Jeu, int argc, char *argv[])
: Lance le jeu avec les arguments données par le joueur
void tour2Jeu (Jeux *Jeu, int argv, char *argc[])
: Lance le jeu et fait une boucle tant que le jeu n'est pas fini
void melangePioche (Jeux *Jeu, int NbrCarteVariante)
void distributionPioche (Jeux *Jeu)
: Distribue la pioche contenu dans la structure Jeu dans les mains des joueurs
void choixCarteEasy (Jeux *Jeu, int idBot)
:Choisit une carte aléatoire dans la main d'un bot
void choixCarteMedium (Jeux *Jeu, int idBot)
: Choisit une carte dans la main du Bot avec l'écart supérieur le plus faible par rapport aux séries
void choixCarteHard (Jeux *Jeu, int idBot)
void creationCarteJoueBot (Jeux *Jeu, int idBot)
: Choisit la carte à jouer du Bot selon la difficulté
void creationCarteJoue (Jeux *Jeu)
: Permet selon le type(bot/humain) de joueur d'attribuer une carte Jouée
void creationOrdrePassage (Jeux *Jeu)
: Permet selon la création d'un tableau de joueur OrdrePassage selon sa carte jouée
void initialiserOrdrePassage (Jeux *Jeu)
: Permet d'initialiser un tableau de joueur OrdrePassage
int choixColonneJoueeBotHard (Jeux *Jeu)
: Permet de choisir la colonne pour le Bot de difficulté Hard
int choixColonneJoueeBotFacile (Jeux *Jeu)
: Le bot facile choisit la colonne avec le plus haut nombre de têtes de boeuf
int choixColonneJoueeHumain (Jeux *Jeu)
: Permet de choisir la colonne de l'humain
int choixColonneJouee (Jeux *Jeu)
: Permet de choisir la colonne selon le type du joueur (humain/bot)
void placementCarteSeries (Jeux *Jeu, int nbCarteNegative, int colonneJouee, int idJoueur)
: Permet de placer la carte selon les séries
int verifSeries (Jeux *Jeu, int colonneJouee)
: Permet de savoir si la colonne est pleine ou non
void decalerSeries (Jeux *Jeu, int colonneJouee, Carte carteJouee)
: Permet de placer une carte en haut d'une colonne tout en décalant les autres cartes vers le bas
void viderSeries (Jeux *Jeu, int colonneJouee, Carte carteJouee, int idJoueur)
: Vide la colonne de la série où le Joueur vient placer sa carte inférieur ou 6è carte supérieur et place la nouvelle carte à la première ligne
void mancheJoueurs (Jeux *Jeu)
: Lance une manche de 10 tours tant que personne atteint le seuil de tête de boeuf
char * intCarteToCharCarte (int valeur)
: Permet de renvoyer un char " 1 " ou " 10" selon le int envoyé
void afficherJeu (Jeux Jeu)
: Permet d'afficher tout le Jeu
Function Documentation
afficherJeu()
void afficherJeu (Jeux Jeu)
: Permet d'afficher tout le Jeu
Authors
: Paul Brechenmacher & Etienne Massonnet
Date
: --—
Precondition
: Prend la stucture Jeu, pour afficher l'entièreté du jeu
Postcondition
: Affichage du jeu
Definition at line 374 of file paul.c.
{
     afficherSeries(Jeu);
 }
References afficherSeries().
Referenced by choixColonneJoueeHumain(), creationCarteJoue(), mancheJoueurs(), and placementSeries().
choixCarteEasy()
: choixCarteEasy (Jeux * Jeu, int idBot)
:Choisit une carte aléatoire dans la main d'un bot
Author
: Paul Brechenmacher
Date
: June 12th, 2023 6:41 PM
Precondition
: Prend le pointeur Bot, pour attribuer une carteJouee aléaoirement avec l'id du Bot
Postcondition
: Bot modifié avec une carte jouée
Definition at line 86 of file paul.c.
{
     int choixCarte;
     do{
         choixCarte = (rand() % 10);
         Jeu->tabJoueurs[idBot].carteJouee = Jeu->tabJoueurs[idBot].mainJoueur[choixCarte];
     }while(Jeu->tabJoueurs[idBot].mainJoueur[choixCarte].carteJouee);
     Jeu->tabJoueurs[idBot].carteJouee.carteJouee = 1;
 }
References Carte::carteJouee, Joueur::carteJouee, Joueur::mainJoueur, and Jeux::tabJoueurs.
Referenced by creationCarteJoueBot().
choixCarteHard()
void choixCarteHard (Jeux * Jeu, int idBot)
Definition at line 117 of file paul.c.
{
     /*
     A définir plus tard pour Etienne
     */
 }
Referenced by creationCarteJoueBot().
choixCarteMedium()
: choixCarteMedium (Jeux * Jeu, int idBot)
: Choisit une carte dans la main du Bot avec l'écart supérieur le plus faible par rapport aux séries
Author
: Paul Brechenmacher
Date
: June 14th, 2023 9:17 PM
Precondition
: Prend le pointeur Bot, pour attribuer une carteJouee aléaoirement avec l'id du Bot
Postcondition
: Bot modifié avec une carte jouée
Definition at line 95 of file paul.c.
{
     int ecartValeur,choixCarte;
     int minEcartValeur = 105;
     for(int idCarteMain = 0; idCarteMain < 10; idCarteMain++){
         /*Si la carte n'a pas était joué*/
         if(!Jeu->tabJoueurs[idBot].mainJoueur[idCarteMain].carteJouee){
             for(int idCarteSeries = 0; idCarteSeries < 4; idCarteSeries++){
                 /* Calcule l'écart entre chaque carte de la main du joueur et chaque 1ère carte des séries*/
                 ecartValeur = Jeu->tabJoueurs[idBot].mainJoueur[idCarteMain].valeur - Jeu->series[0][idCarteSeries].valeur;
                 if(ecartValeur > 0){
                     if(ecartValeur < minEcartValeur){
                         minEcartValeur = ecartValeur;
                         choixCarte = idCarteMain;
                     }
                 }
             }
         }
     }
     Jeu->tabJoueurs[idBot].carteJouee = Jeu->tabJoueurs[idBot].mainJoueur[choixCarte];
     Jeu->tabJoueurs[idBot].carteJouee.carteJouee = 1;
 }
References Carte::carteJouee, Joueur::carteJouee, Joueur::mainJoueur, Jeux::series, Jeux::tabJoueurs, and Carte::valeur.
Referenced by creationCarteJoueBot().
choixColonneJouee()
: choixColonneJouee (Jeux * Jeu)
: Permet de choisir la colonne selon le type du joueur (humain/bot)
Author
: Paul Brechenmacher
Date
: June 14th, 2023 2:02 AM
Precondition
: Prend le pointeur Jeu, pour l'ordre de Passage
Postcondition
: Renvoie un entier colonneJouee (0 à 3)
Definition at line 252 of file paul.c.
{
     int colonneJouee;
     if(Jeu->ordreDePassage[0].type == HUMAIN){
         colonneJouee = choixColonneJoueeHumain(Jeu);
     }else{
         printf(BWHT"%s choisit une colonne entre 1 et 4 ...\n"reset,Jeu->ordreDePassage[0].nomJoueur);
         #ifdef NOSLEEP
         #else
             sleep(2);
         #endif
         switch (Jeu->niveauBots)
         {
         case EASY:
             colonneJouee = choixColonneJoueeBotFacile(Jeu);
             break;
         case MEDIUM:
             colonneJouee = (rand() % 4);
             break;
         case HARD:
             colonneJouee = choixColonneJoueeBotHard(Jeu);
             break;
         default:
             break;
         }
     }
     return colonneJouee;
 }
References BWHT, choixColonneJoueeBotFacile(), choixColonneJoueeBotHard(), choixColonneJoueeHumain(), EASY, HARD, HUMAIN, MEDIUM, Jeux::niveauBots, Joueur::nomJoueur, Jeux::ordreDePassage, reset, and Joueur::type.
Referenced by placementCarteSeries().
choixColonneJoueeBotFacile()
: choixColonneJoueeBotFacile (Jeux * Jeu)
: Le bot facile choisit la colonne avec le plus haut nombre de têtes de boeuf
Author
: Paul Brechenmacher
Date
: 14 Juin 2023
Precondition
: Prend le pointeur Jeu, pour les séries
Postcondition
: Renvoie un entier colonneJouee
Definition at line 216 of file paul.c.
{
     int colonneJouee,nbBoeuf;
     int nbMaxBoeuf = 0;
     for(int idColonne = 0; idColonne < 4; idColonne++){
         nbBoeuf = 0;
         for(int idLigne = 0; idLigne < 5; idLigne++){
             nbBoeuf = nbBoeuf + Jeu->series[idLigne][idColonne].teteDeboeuf;
         }
         if(nbBoeuf > nbMaxBoeuf){
             nbMaxBoeuf = nbBoeuf;
             colonneJouee = idColonne;
         }
     }
     return colonneJouee;
 }
References Jeux::series, and Carte::teteDeboeuf.
Referenced by choixColonneJouee().
choixColonneJoueeBotHard()
: choixColonneJoueeBotHard (Jeux * Jeu)
: Permet de choisir la colonne pour le Bot de difficulté Hard
Author
: Paul Brechenmacher
Date
: 14 Juin 2023
Precondition
: Prend le pointeur Jeu, pour les séries
Postcondition
: Renvoie un entier colonneJouee
Definition at line 199 of file paul.c.
{
     int colonneJouee,nbBoeuf;
     int nbMinBoeuf = 100;
     for(int idColonne = 0; idColonne < 4; idColonne++){
         nbBoeuf = 0;
         for(int idLigne = 0; idLigne < 5; idLigne++){
             nbBoeuf = nbBoeuf + Jeu->series[idLigne][idColonne].teteDeboeuf;
         }
         if(nbBoeuf < nbMinBoeuf){
             nbMinBoeuf = nbBoeuf;
             colonneJouee = idColonne;
         }
     }
     return colonneJouee;
 }
References Jeux::series, and Carte::teteDeboeuf.
Referenced by choixColonneJouee().
choixColonneJoueeHumain()
choixColonneJoueeHumain (Jeux * Jeu)
: Permet de choisir la colonne de l'humain
Author
: Paul Brechenmacher
Date
: June 14th, 2023 2:02 AM
Precondition
: Prend le pointeur Jeu, pour l'ordre de Passage (affichade des carte de chaque joueur)
Postcondition
: Renvoie un entier colonneJouee (0 à 3)
Definition at line 233 of file paul.c.
{
     int colonneJouee;
     do{
         system("clear");
         afficherJeu(*Jeu);
         for(int idPassage = 0; idPassage < Jeu->nbJoueurs; idPassage++){
             afficherCarte(Jeu->ordreDePassage[idPassage].carteJouee,CARTE_MAIN_NONJOUE);
             printf(" - Carte de %s\n",Jeu->ordreDePassage[idPassage].nomJoueur);
         }
         printf(BWHT"%s doit choisir une colonne entre 1 et 4 :\n"reset,Jeu->ordreDePassage[0].nomJoueur);
         scanf("%d",&colonneJouee);
         emptyBuffer();
         system("clear");
     }while(colonneJouee < 1 || colonneJouee > 4);
     return colonneJouee-1;
 }
References afficherCarte(), afficherJeu(), BWHT, CARTE_MAIN_NONJOUE, Joueur::carteJouee, emptyBuffer(), Jeux::nbJoueurs, Joueur::nomJoueur, Jeux::ordreDePassage, and reset.
Referenced by choixColonneJouee().
creationCarteJoue()
: creationCarteJoue (Jeux * Jeu)
: Permet selon le type(bot/humain) de joueur d'attribuer une carte Jouée
Author
: Paul Brechenmacher
Date
: 31 mai
Precondition
: Prend le pointeur Jeu, pour prendre la Jeu.tabjoueur[id].type/.nomJoueur et
Postcondition
: Jeu.tabjoueur[id].carteJouee modifié ainsi que l'état de la carteJouée dans la main
Definition at line 147 of file paul.c.
{
     //int nbTours = Jeu->nbTours;
     int choixCarte = 0;
     //char input[100];
     for(int idjoueur = 0; idjoueur < Jeu->nbJoueurs; idjoueur++){
         if(Jeu->tabJoueurs[idjoueur].type){
             system("clear");
             do{
                 afficherJeu(*Jeu);
                 printf(BWHT"\e[4;37m" "Main de %s :\n\n"reset,Jeu->tabJoueurs[idjoueur].nomJoueur);
                 afficherMainJoueur(&Jeu->tabJoueurs[idjoueur]);
                 printf(BWHT"\n\nChoisissez une carte entre 1 et %d :\n"reset,Jeu->tabJoueurs[idjoueur].nb_cartes);
                 scanf("%d", &choixCarte);
                 emptyBuffer();
                 system("clear");
             }while(Jeu->tabJoueurs[idjoueur].mainJoueur[choixCarte-1].carteJouee || choixCarte < 1 || choixCarte > Jeu->tabJoueurs[idjoueur].nb_cartes);
         }else{
             creationCarteJoueBot(Jeu,idjoueur);
         }
         Jeu->tabJoueurs[idjoueur].carteJouee = Jeu->tabJoueurs[idjoueur].mainJoueur[choixCarte-1];
         Jeu->tabJoueurs[idjoueur].mainJoueur[choixCarte-1].carteJouee = 1;
         supprimercarte(Jeu->tabJoueurs[idjoueur].mainJoueur, &Jeu->tabJoueurs[idjoueur].nb_cartes, choixCarte-1);
     }
 }
References afficherJeu(), afficherMainJoueur(), BWHT, Carte::carteJouee, Joueur::carteJouee, creationCarteJoueBot(), emptyBuffer(), Joueur::mainJoueur, Joueur::nb_cartes, Jeux::nbJoueurs, Joueur::nomJoueur, reset, supprimercarte(), Jeux::tabJoueurs, and Joueur::type.
Referenced by creationOrdrePassage().
creationCarteJoueBot()
: creationCarteJoueBot (Jeux * Jeu, int idBot)
: Choisit la carte à jouer du Bot selon la difficulté
Author
: Paul Brechenmacher
Date
: June 14th, 2023 9:17 PM
Precondition
: Pointeur Jeu et id dans le tabJoueur
Postcondition
: carteJouee sélectioné du joueur Bot.
Definition at line 126 of file paul.c.
{
     switch (Jeu->niveauBots)
     {
     case EASY:
         choixCarteEasy(Jeu,idBot);
         break;
     case MEDIUM:
         choixCarteMedium(Jeu,idBot);
         break;
     case HARD:
         choixCarteHard(Jeu,idBot);
         break;
     default:
         printf("ERREUR DE DIFFICULTÉ\n");
         break;
     }
 }
References choixCarteEasy(), choixCarteHard(), choixCarteMedium(), EASY, HARD, MEDIUM, and Jeux::niveauBots.
Referenced by creationCarteJoue().
creationOrdrePassage()
: creationOrdrePassage (Jeux * Jeu)
: Permet selon la création d'un tableau de joueur OrdrePassage selon sa carte jouée
Author
: Paul Brechenmacher
Date
: 31 mai
Precondition
: Prend le pointeur Jeu, pour prendre la Jeu.tabjoueur et l'ordre de passage
Postcondition
: Jeu.ordreDePassage modifié selon les mains des joueurs
Definition at line 172 of file paul.c.
{
     creationCarteJoue(Jeu);
     for(int idjoueur = 0; idjoueur < Jeu->nbJoueurs; idjoueur++){
         Jeu->ordreDePassage[idjoueur] = Jeu->tabJoueurs[idjoueur] ;
     }
     Joueur tempJoueur;
     int eltEncours;
     for(int i=1; i < Jeu->nbJoueurs; i++){
         eltEncours = i;
         while(Jeu->ordreDePassage[eltEncours].carteJouee.valeur < Jeu->ordreDePassage[eltEncours-1].carteJouee.valeur && eltEncours > 0){
             tempJoueur =  Jeu->ordreDePassage[eltEncours];
             Jeu->ordreDePassage[eltEncours] = Jeu->ordreDePassage[eltEncours-1];
             Jeu->ordreDePassage[eltEncours-1] = tempJoueur;
             eltEncours--;
         }
     }
 }
References Joueur::carteJouee, creationCarteJoue(), Jeux::nbJoueurs, Jeux::ordreDePassage, Jeux::tabJoueurs, and Carte::valeur.
Referenced by mancheJoueurs().
decalerSeries()
: decalerSeries (Jeux * Jeu, int colonneJouee, Carte carteJouee)
: Permet de placer une carte en haut d'une colonne tout en décalant les autres cartes vers le bas
Authors
: Paul Brechenmacher & Etienne Massonnet
Date
: June 12th, 2023 4:01 PM
Precondition
: Prend le pointeur Jeu pour décaler chaque élement de la colonne jouée et sa carteJouée à placer en haut de la colonne
Postcondition
: Modification des séries
Definition at line 307 of file paul.c.
{
     for(int l = 4; l > 0 ;l--){
         Jeu->series[l][colonneJouee] = Jeu->series[l-1][colonneJouee];
     }
     Jeu->series[0][colonneJouee] = carteJouee;
 }
References Jeux::series.
Referenced by placementCarteSeries().
distributionPioche()
: distributionPioche (Jeux * Jeu)
: Distribue la pioche contenu dans la structure Jeu dans les mains des joueurs
Author
: Paul Brechenmacher
Date
: May 25th, 2023 3:53 PM
Precondition
: Prend le pointeur Jeu, pour prendre la Jeu.pioche et les main des Joueurs
Postcondition
: Les mains de chaque joueurs sont modifiées
Definition at line 72 of file paul.c.
{
     int idCartePioche = 0;
     for(int idJoueur = 0; idJoueur < Jeu->nbJoueurs;idJoueur++){
         int idCarteMain = 0;
         while(idCarteMain < 10){
             Jeu->tabJoueurs[idJoueur].mainJoueur[idCarteMain] = Jeu->pioche[idCartePioche];
             idCartePioche++;
             idCarteMain++;
         }
     }
     printf("\nDistribution Pioche\n");
 }
References Joueur::mainJoueur, Jeux::nbJoueurs, Jeux::pioche, and Jeux::tabJoueurs.
Referenced by tour2Jeu().
initialiserOrdrePassage()
: initialiserOrdrePassage (Jeux * Jeu)
: Permet d'initialiser un tableau de joueur OrdrePassage
Author
: Paul Brechenmacher
Date
: 31 mai
Precondition
: Prend le pointeur Jeu, pour allouer un tableau dynamique de taille nbJoueur
Postcondition
: tableau OrdreDePassage initialisé
Definition at line 192 of file paul.c.
{
     for(int idJoueur = 0; idJoueur < Jeu->nbJoueurs; idJoueur++){
         Jeu->tabJoueurs[idJoueur].nb_cartes = 10;
     }
     Jeu->ordreDePassage = malloc(Jeu->nbJoueurs * sizeof(Joueur));
 }
References Joueur::nb_cartes, Jeux::nbJoueurs, Jeux::ordreDePassage, and Jeux::tabJoueurs.
Referenced by mancheJoueurs().
intCarteToCharCarte()
: intCarteToCharCarte (int valeur)
: Permet de renvoyer un char " 1 " ou " 10" selon le int envoyé
Authors
: Paul Brechenmacher & Etienne Massonnet
Date
: June 13th, 2023 7:52 PM
Precondition
: Prend un entier la valeur de la carte
Postcondition
: Renvoie un char permettant d'éviter les décalages sur les séries
Definition at line 355 of file paul.c.
{
     char* charValue;
     charValue = malloc(5 * sizeof(char));
     char buffer[5];
     if(valeur < 10){
         sprintf(buffer," %d ",valeur);
         charValue = strdup(buffer);
     }else{
         if(valeur>99){
             sprintf(buffer,"%d",valeur);
             charValue = strdup(buffer);
         }else{
             sprintf(buffer," %d",valeur);
             charValue = strdup(buffer);
         }
     }
     return charValue;
 }
Referenced by afficherCarte().
mancheJoueurs()
: mancheJoueurs (Jeux * Jeu)
: Lance une manche de 10 tours tant que personne atteint le seuil de tête de boeuf
Authors
: Paul Brechenmacher & Adrien Le Mée Moret
Date
: June 12th, 2023 4:01 PM
Precondition
: Prend le pointeur Jeu pour accéder ensuite à l'ordre de Passage et accéder aux différents joueurs
Postcondition
: Renvoie un classement final quand un joueur atteint le seuil de tête de boeuf et stop la procédure
Definition at line 338 of file paul.c.
{
     int nbTours = 0;
     initialiserOrdrePassage(Jeu);
     while(Jeu->etatduJeu && nbTours <10){
         creationOrdrePassage(Jeu);
         placementSeries(Jeu);
         system("clear");
         afficherJeu(*Jeu);
         nbTours++;
     }
     if(Jeu->etatduJeu){
         afficherAbattoir(*Jeu);
         sleep(2);
     }
 }
References afficherAbattoir(), afficherJeu(), creationOrdrePassage(), Jeux::etatduJeu, initialiserOrdrePassage(), and placementSeries().
Referenced by tour2Jeu().
melangePioche()
void melangePioche (Jeux * Jeu, int NbrCarteVariante)
Definition at line 59 of file paul.c.
{
     Carte tempCarte;
     int idRandom;
     srand(time(NULL));
     for(int idcarte = 0; idcarte < NbrCarteVariante ;idcarte++){
         tempCarte = Jeu->pioche[idcarte];
         idRandom = rand() % NbrCarteVariante;
         Jeu->pioche[idcarte] = Jeu->pioche[idRandom];
         Jeu->pioche[idRandom] = tempCarte;
     }
     printf("\nMélange Pioche\n");
 }
References Jeux::pioche.
Referenced by tour2Jeu().
placementCarteSeries()
: placementCarteSeries (Jeux * Jeu, int nbCarteNegative, int colonneJouee, int idJoueur)
: Permet de placer la carte selon les séries
Authors
: Paul Brechenmacher & Etienne Massonnet & Nathan Goncalves
Date
: June 12th, 2023 4:01 PM
Precondition
: Prend le pointeur Jeu pour modifier ensuite les séries, le nbCarteNégative le nombre de carte inférieur sur les séries, la colonne ou la carte doit être jouée et l'id du joueur dans le tabJoueur
Postcondition
: Les séries ont était mises à jour avec les cartes jouées par les joueurs
Definition at line 284 of file paul.c.
{
     if(nbCarteNegative > 3){
         system("clear");
         printf("\n");
         colonneJouee = choixColonneJouee(Jeu);
         viderSeries(Jeu,colonneJouee,Jeu->ordreDePassage[idJoueur].carteJouee,Jeu->ordreDePassage[idJoueur].id);
     }else{
         if(verifSeries(Jeu,colonneJouee)){// si 1 plein sinon c'est 0 reste de la place
             viderSeries(Jeu,colonneJouee,Jeu->ordreDePassage[idJoueur].carteJouee,Jeu->ordreDePassage[idJoueur].id);
         }else{
             decalerSeries(Jeu,colonneJouee,Jeu->ordreDePassage[idJoueur].carteJouee);
         }
     }
 }
References Joueur::carteJouee, choixColonneJouee(), decalerSeries(), Joueur::id, Jeux::ordreDePassage, verifSeries(), and viderSeries().
Referenced by placementSeries().
startJeu()
: startJeu (Jeux * Jeu, int argc, char * argv[])
: Lance le jeu avec les arguments données par le joueur
Authors
: Paul Brechenmacher & Etienne Massonnet & Adrien Le Mée Moret & Nathan Goncalves
Date
: -—
Precondition
: Prend le pointeur Jeu, et les arguments du ./exe effectué par le joueur
Postcondition
: Jeu lancé avec une pioche et des mains pour tous les joueurs
Definition at line 9 of file paul.c.
{
     affichageLogo();
     lancementArg(Jeu, argc, argv);
     creationPioche(Jeu);
     system("clear");
     Jeu->etatduJeu = 1;
 }
References affichageLogo(), creationPioche(), Jeux::etatduJeu, and lancementArg().
Referenced by tour2Jeu().
tour2Jeu()
: tour2Jeu (Jeux * Jeu, int argv, char * argc[])
: Lance le jeu et fait une boucle tant que le jeu n'est pas fini
Author
: Paul Brechenmacher
Date
: June 13th, 2023 4:13 PM
Precondition
: Prend le pointeur Jeu et les arguments du ./exe
Postcondition
: Le jeu est terminé
Definition at line 19 of file paul.c.
{
     startJeu(Jeu, argv, argc);
     switch (Jeu->variante){
         case CLASSIQUE:
             while(Jeu->etatduJeu){
                 melangePioche(Jeu,104);
                 creationSeries(Jeu);
                 distributionPioche(Jeu);
                 system("clear");
                 mancheJoueurs(Jeu);
             }
             break;
         case NB_DEFINIS:
             while(Jeu->etatduJeu){
                 melangePioche(Jeu,(Jeu->nbJoueurs*10)+4);
                 creationSeries(Jeu);
                 distributionPioche(Jeu);
                 system("clear");
                 mancheJoueurs(Jeu);
             }
             break;
         case DRAFT:
             while(Jeu->etatduJeu){
                 distributionPiocheDraft(Jeu);
                 creationSeriesDraft(Jeu);
                 system("clear");
                 mancheJoueurs(Jeu);
             }
             break;
         default:
             break;
     }
     classement(Jeu);
     affclassement(Jeu);
 }
References affclassement(), classement(), CLASSIQUE, creationSeries(), creationSeriesDraft(), distributionPioche(), distributionPiocheDraft(), DRAFT, Jeux::etatduJeu, mancheJoueurs(), melangePioche(), NB_DEFINIS, Jeux::nbJoueurs, startJeu(), and Jeux::variante.
Referenced by main().
verifSeries()
: verifSeries (Jeux * Jeu, int colonneJouee)
: Permet de savoir si la colonne est pleine ou non
Authors
: Paul Brechenmacher & Nathan Goncalves
Date
: June 12th, 2023 4:01 PM
Precondition
: Prend le pointeur Jeu pour vérifier dans les séries si la colonne est pleine, la colonne jouée
Postcondition
: Retourne 0 si vide, 1 si plein
Definition at line 299 of file paul.c.
{
     int value = 1;
     if(Jeu->series[4][colonneJouee].valeur == 0 && Jeu->series[4][colonneJouee].teteDeboeuf == 0 ){
         value = 0;
     }
     return value;
 }
References Jeux::series, Carte::teteDeboeuf, and Carte::valeur.
Referenced by placementCarteSeries().
viderSeries()
: viderSeries (Jeux * Jeu, int colonneJouee, Carte carteJouee, int idJoueur)
: Vide la colonne de la série où le Joueur vient placer sa carte inférieur ou 6è carte supérieur et place la nouvelle carte à la première ligne
Authors
: Paul Brechenmacher & Adrien Le Mée Moret
Date
: June 12th, 2023 4:01 PM
Precondition
: Prend le pointeur Jeu pour vider chaque élement de la colonne jouée, et sa carteJouée à placer en haut de la colonne
Postcondition
: Modification des séries
Definition at line 314 of file paul.c.
{
     int ecartAbattoir,tempAbattoir;
     tempAbattoir = Jeu->tabJoueurs[idJoueur].abattoirJoueur;
     for(int l = 0; l < 5;l++){
         Jeu->tabJoueurs[idJoueur].abattoirJoueur = Jeu->tabJoueurs[idJoueur].abattoirJoueur + Jeu->series[l][colonneJouee].teteDeboeuf;
     }
     ecartAbattoir = Jeu->tabJoueurs[idJoueur].abattoirJoueur - tempAbattoir;
     printf(BRED"\n+%d"BWHT" dans l'abattoir de %s qui contient maintenant "BRED"%d"BWHT" TDB\n"reset,ecartAbattoir,Jeu->tabJoueurs[idJoueur].nomJoueur,Jeu->tabJoueurs[idJoueur].abattoirJoueur);
     #ifdef NOSLEEP
     #else
         sleep(2);
     #endif
     for(int l = 0; l < 5 ; l++){
         Carte NeutreCarte;
         NeutreCarte.teteDeboeuf = 0;
         NeutreCarte.valeur = 0;
         Jeu->series[l][colonneJouee] = NeutreCarte;
     }
     Jeu->series[0][colonneJouee] = carteJouee;
 }
References Joueur::abattoirJoueur, BRED, BWHT, Joueur::nomJoueur, reset, Jeux::series, Jeux::tabJoueurs, Carte::teteDeboeuf, and Carte::valeur.
Referenced by placementCarteSeries().